# -*- coding: utf-8 -*-
"""LangGraph-SelfRag(v1) vs Deepnxyz-SelfRag(v4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rodzm1JOujwa3tRoEDdGrPZg9agHRQyI
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set seaborn style for better aesthetics
sns.set_style("whitegrid")

# Precision lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
precision_v1_new = [
    0.8120, 0.8550, 0.8412, 0.8650, 0.8860, 0.8719, 0.8860, 0.9222, 0.8724, 0.9270,
    0.9673, 0.9505, 0.8686, 0.9337, 0.9233, 0.8264, 0.8959, 0.9364, 0.8739, 0.9454,
    0.9363, 0.9173, 0.9334, 0.9587, 0.9049, 0.9539, 0.9345, 0.9569, 0.9305, 0.9333,
    0.9367, 0.9167, 0.9563, 0.8737, 0.8799, 0.8743, 0.9314, 0.9211,
    0.9215, 0.9398, 0.9129, 0.8643, 0.9679, 0.8711, 0.9589, 0.8945, 0.9014
]
precision_v4_new = [
    0.8244, 0.8936, 0.8974, 0.8312, 0.9018, 0.8812, 0.8630, 0.9219, 0.8752, 0.9275,
    0.9539, 0.8497, 0.8632, 0.9139, 0.9236, 0.8764, 0.8922, 0.9265, 0.8840, 0.9288,
    0.9441, 0.8954, 0.9278, 0.9084, 0.9093, 0.9513, 0.9295, 0.9513, 0.9510, 0.9485,
    0.8894, 0.9185, 0.9585, 0.8449, 0.8615, 0.8569, 0.9541, 0.9149,
    0.9084, 0.8883, 0.8721, 0.9138, 0.8869, 0.9023, 0.9527, 0.9114, 0.8942
]

# Recall lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
recall_v1_new = [
    0.8834, 0.8686, 0.8549, 0.8248, 0.8676, 0.8830, 0.9013, 0.9213, 0.8662, 0.9284,
    0.9465, 0.9278, 0.8485, 0.8967, 0.9069, 0.8320, 0.8667, 0.8564, 0.8556, 0.9755,
    0.9291, 0.8897, 0.9280, 0.9397, 0.8846, 0.9327, 0.9087, 0.9287, 0.9418, 0.9342,
    0.9214, 0.9065, 0.9619, 0.8689, 0.8956, 0.8704, 0.8657, 0.9298,
    0.8766, 0.9232, 0.8975, 0.8675, 0.9793, 0.8729, 0.9495, 0.8622, 0.8739
]
recall_v4_new = [
    0.8771, 0.8890, 0.8570, 0.8411, 0.8678, 0.9183, 0.8739, 0.9197, 0.8472, 0.9212,
    0.8909, 0.8454, 0.8220, 0.8961, 0.8620, 0.8583, 0.8668, 0.8642, 0.8600, 0.9688,
    0.9219, 0.8829, 0.9213, 0.9177, 0.8918, 0.9261, 0.9086, 0.9184, 0.9134, 0.9333,
    0.9290, 0.9115, 0.9608, 0.8721, 0.8837, 0.8598, 0.8688, 0.9223,
    0.8932, 0.9119, 0.8602, 0.9098, 0.8996, 0.9301, 0.9222, 0.8703, 0.8662
]

# F1-score lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
f1_v1_new = [
    0.8462, 0.8795, 0.8480, 0.8444, 0.8767, 0.8774, 0.8936, 0.9218, 0.8693, 0.9277,
    0.9568, 0.9390, 0.8533, 0.9149, 0.9150, 0.8292, 0.8810, 0.8946, 0.8647, 0.9602,
    0.9327, 0.9033, 0.9307, 0.9491, 0.8947, 0.9432, 0.9214, 0.9426, 0.9361, 0.9338,
    0.9290, 0.9115, 0.9591, 0.8713, 0.8877, 0.8723, 0.8973, 0.9254,
    0.8985, 0.9314, 0.9051, 0.8659, 0.9736, 0.8720, 0.9543, 0.8781, 0.8874
]
f1_v4_new = [
    0.8499, 0.8913, 0.8767, 0.8361, 0.8845, 0.8994, 0.8684, 0.9208, 0.8610, 0.9244,
    0.9213, 0.8475, 0.8421, 0.9049, 0.8917, 0.8673, 0.8793, 0.8943, 0.8718, 0.9484,
    0.9329, 0.8891, 0.9245, 0.9130, 0.9005, 0.9385, 0.9190, 0.9346, 0.9318, 0.9408,
    0.9088, 0.9150, 0.9596, 0.8582, 0.8725, 0.8584, 0.9094, 0.9185,
    0.9008, 0.9000, 0.8661, 0.9118, 0.8932, 0.9160, 0.9372, 0.8904, 0.8800
]

# Corrected question indices (1-based, excluding q35, q36, q48)
question_indices = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47
]

# Verify lengths
print(f"Length of question_indices: {len(question_indices)}")
print(f"Length of precision_v1_new: {len(precision_v1_new)}")
print(f"Length of precision_v4_new: {len(precision_v4_new)}")
print(f"Length of recall_v1_new: {len(recall_v1_new)}")
print(f"Length of recall_v4_new: {len(recall_v4_new)}")
print(f"Length of f1_v1_new: {len(f1_v1_new)}")
print(f"Length of f1_v4_new: {len(f1_v4_new)}")

# Plot only if lengths match
if len(question_indices) == len(precision_v1_new) == len(precision_v4_new) == len(recall_v1_new) == len(recall_v4_new) == len(f1_v1_new) == len(f1_v4_new):
    # Create figure with three subplots
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(14, 18), sharex=True)

    # Precision subplot
    ax1.plot(question_indices, precision_v1_new, marker='o', linewidth=2, markersize=7,
             label='Self RAG v1 Precision', color='#1f77b4')
    ax1.plot(question_indices, precision_v4_new, marker='s', linewidth=2, markersize=7,
             label='Self RAG v4 Precision', color='#ff7f0e')
    ax1.set_title('Precision Comparison: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax1.set_ylabel('Precision', fontsize=14, labelpad=10)
    ax1.legend(fontsize=12, loc='best', frameon=True, shadow=True)
    ax1.set_ylim(0.7, 1.0)
    ax1.grid(True, linestyle='--', alpha=0.7)
    ax1.tick_params(axis='y', labelsize=10)

    # Recall subplot
    ax2.plot(question_indices, recall_v1_new, marker='o', linewidth=2, markersize=7,
             label='Self RAG v1 Recall', color='#1f77b4')
    ax2.plot(question_indices, recall_v4_new, marker='s', linewidth=2, markersize=7,
             label='Self RAG v4 Recall', color='#ff7f0e')
    ax2.set_title('Recall Comparison: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax2.set_ylabel('Recall', fontsize=14, labelpad=10)
    ax2.legend(fontsize=12, loc='best', frameon=True, shadow=True)
    ax2.set_ylim(0.7, 1.0)
    ax2.grid(True, linestyle='--', alpha=0.7)
    ax2.tick_params(axis='y', labelsize=10)

    # F1-score subplot
    ax3.plot(question_indices, f1_v1_new, marker='o', linewidth=2, markersize=7,
             label='Self RAG v1 F1-Score', color='#1f77b4')
    ax3.plot(question_indices, f1_v4_new, marker='s', linewidth=2, markersize=7,
             label='Self RAG v4 F1-Score', color='#ff7f0e')
    ax3.set_title('F1-Score Comparison: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax3.set_xlabel('Question Index', fontsize=14, labelpad=10)
    ax3.set_ylabel('F1-Score', fontsize=14, labelpad=10)
    ax3.legend(fontsize=12, loc='best', frameon=True, shadow=True)
    ax3.set_ylim(0.7, 1.0)
    ax3.grid(True, linestyle='--', alpha=0.7)
    ax3.set_xticks(question_indices)
    ax3.tick_params(axis='x', labelsize=10, rotation=45)
    ax3.tick_params(axis='y', labelsize=10)

    # Adjust layout
    plt.tight_layout()

    # Save and show the plot
    plt.savefig('precision_recall_f1_comparison.png', dpi=300)
    plt.show()
else:
    print("Error: Data lengths do not match. Please check the input data.")

import matplotlib.pyplot as plt
import seaborn as sns

# Set seaborn style for better aesthetics
sns.set_style("whitegrid")

# Precision lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
precision_v1_new = [
    0.8120, 0.8550, 0.8412, 0.8650, 0.8860, 0.8719, 0.8860, 0.9222, 0.8724, 0.9270,
    0.9673, 0.9505, 0.8686, 0.9337, 0.9233, 0.8264, 0.8959, 0.9364, 0.8739, 0.9454,
    0.9363, 0.9173, 0.9334, 0.9587, 0.9049, 0.9539, 0.9345, 0.9569, 0.9305, 0.9333,
    0.9367, 0.9167, 0.9563, 0.8737, 0.8799, 0.8743, 0.9314, 0.9211,
    0.9215, 0.9398, 0.9129, 0.8643, 0.9679, 0.8711, 0.9589, 0.8945, 0.9014
]
precision_v4_new = [
    0.8244, 0.8936, 0.8974, 0.8312, 0.9018, 0.8812, 0.8630, 0.9219, 0.8752, 0.9275,
    0.9539, 0.8497, 0.8632, 0.9139, 0.9236, 0.8764, 0.8922, 0.9265, 0.8840, 0.9288,
    0.9441, 0.8954, 0.9278, 0.9084, 0.9093, 0.9513, 0.9295, 0.9513, 0.9510, 0.9485,
    0.8894, 0.9185, 0.9585, 0.8449, 0.8615, 0.8569, 0.9541, 0.9149,
    0.9084, 0.8883, 0.8721, 0.9138, 0.8869, 0.9023, 0.9527, 0.9114, 0.8942
]

# Recall lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
recall_v1_new = [
    0.8834, 0.8686, 0.8549, 0.8248, 0.8676, 0.8830, 0.9013, 0.9213, 0.8662, 0.9284,
    0.9465, 0.9278, 0.8485, 0.8967, 0.9069, 0.8320, 0.8667, 0.8564, 0.8556, 0.9755,
    0.9291, 0.8897, 0.9280, 0.9397, 0.8846, 0.9327, 0.9087, 0.9287, 0.9418, 0.9342,
    0.9214, 0.9065, 0.9619, 0.8689, 0.8956, 0.8704, 0.8657, 0.9298,
    0.8766, 0.9232, 0.8975, 0.8675, 0.9793, 0.8729, 0.9495, 0.8622, 0.8739
]
recall_v4_new = [
    0.8771, 0.8890, 0.8570, 0.8411, 0.8678, 0.9183, 0.8739, 0.9197, 0.8472, 0.9212,
    0.8909, 0.8454, 0.8220, 0.8961, 0.8620, 0.8583, 0.8668, 0.8642, 0.8600, 0.9688,
    0.9219, 0.8829, 0.9213, 0.9177, 0.8918, 0.9261, 0.9086, 0.9184, 0.9134, 0.9333,
    0.9290, 0.9115, 0.9608, 0.8721, 0.8837, 0.8598, 0.8688, 0.9223,
    0.8932, 0.9119, 0.8602, 0.9098, 0.8996, 0.9301, 0.9222, 0.8703, 0.8662
]

# F1-score lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
f1_v1_new = [
    0.8462, 0.8795, 0.8480, 0.8444, 0.8767, 0.8774, 0.8936, 0.9218, 0.8693, 0.9277,
    0.9568, 0.9390, 0.8533, 0.9149, 0.9150, 0.8292, 0.8810, 0.8946, 0.8647, 0.9602,
    0.9327, 0.9033, 0.9307, 0.9491, 0.8947, 0.9432, 0.9214, 0.9426, 0.9361, 0.9338,
    0.9290, 0.9115, 0.9591, 0.8713, 0.8877, 0.8723, 0.8973, 0.9254,
    0.8985, 0.9314, 0.9051, 0.8659, 0.9736, 0.8720, 0.9543, 0.8781, 0.8874
]
f1_v4_new = [
    0.8499, 0.8913, 0.8767, 0.8361, 0.8845, 0.8994, 0.8684, 0.9208, 0.8610, 0.9244,
    0.9213, 0.8475, 0.8421, 0.9049, 0.8917, 0.8673, 0.8793, 0.8943, 0.8718, 0.9484,
    0.9329, 0.8891, 0.9245, 0.9130, 0.9005, 0.9385, 0.9190, 0.9346, 0.9318, 0.9408,
    0.9088, 0.9150, 0.9596, 0.8582, 0.8725, 0.8584, 0.9094, 0.9185,
    0.9008, 0.9000, 0.8661, 0.9118, 0.8932, 0.9160, 0.9372, 0.8904, 0.8800
]

# Verify lengths
print(f"Length of precision_v1_new: {len(precision_v1_new)}")
print(f"Length of precision_v4_new: {len(precision_v4_new)}")
print(f"Length of recall_v1_new: {len(recall_v1_new)}")
print(f"Length of recall_v4_new: {len(recall_v4_new)}")
print(f"Length of f1_v1_new: {len(f1_v1_new)}")
print(f"Length of f1_v4_new: {len(f1_v4_new)}")

# Plot only if lengths match
if len(precision_v1_new) == len(precision_v4_new) == len(recall_v1_new) == len(recall_v4_new) == len(f1_v1_new) == len(f1_v4_new):
    # Create figure with three subplots
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(12, 15))

    # Precision histogram
    sns.histplot(data=precision_v1_new, bins=10, color='#1f77b4', alpha=0.5, label='Self RAG v1 Precision', ax=ax1)
    sns.histplot(data=precision_v4_new, bins=10, color='#ff7f0e', alpha=0.5, label='Self RAG v4 Precision', ax=ax1)
    ax1.set_title('Precision Distribution: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax1.set_xlabel('Precision', fontsize=14, labelpad=10)
    ax1.set_ylabel('Frequency', fontsize=14, labelpad=10)
    ax1.legend(fontsize=12, frameon=True, shadow=True)
    ax1.set_xlim(0.7, 1.0)
    ax1.tick_params(axis='both', labelsize=10)

    # Recall histogram
    sns.histplot(data=recall_v1_new, bins=10, color='#1f77b4', alpha=0.5, label='Self RAG v1 Recall', ax=ax2)
    sns.histplot(data=recall_v4_new, bins=10, color='#ff7f0e', alpha=0.5, label='Self RAG v4 Recall', ax=ax2)
    ax2.set_title('Recall Distribution: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax2.set_xlabel('Recall', fontsize=14, labelpad=10)
    ax2.set_ylabel('Frequency', fontsize=14, labelpad=10)
    ax2.legend(fontsize=12, frameon=True, shadow=True)
    ax2.set_xlim(0.7, 1.0)
    ax2.tick_params(axis='both', labelsize=10)

    # F1-score histogram
    sns.histplot(data=f1_v1_new, bins=10, color='#1f77b4', alpha=0.5, label='Self RAG v1 F1-Score', ax=ax3)
    sns.histplot(data=f1_v4_new, bins=10, color='#ff7f0e', alpha=0.5, label='Self RAG v4 F1-Score', ax=ax3)
    ax3.set_title('F1-Score Distribution: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    ax3.set_xlabel('F1-Score', fontsize=14, labelpad=10)
    ax3.set_ylabel('Frequency', fontsize=14, labelpad=10)
    ax3.legend(fontsize=12, frameon=True, shadow=True)
    ax3.set_xlim(0.7, 1.0)
    ax3.tick_params(axis='both', labelsize=10)

    # Adjust layout
    plt.tight_layout()

    # Save and show the plot
    plt.savefig('precision_recall_f1_histogram_comparison.png', dpi=300)
    plt.show()
else:
    print("Error: Data lengths do not match. Please check the input data.")

import matplotlib.pyplot as plt
import seaborn as sns

# Set seaborn style for better aesthetics
sns.set_style("whitegrid")

# Response time lists excluding q35 (index 34), q36 (index 35), and q48 (index 47)
response_time_v1_new = [
    35.48, 137.38, 41.32, 61.92, 49.37, 58.22, 42.55, 44.69, 73.78, 56.07,
    52.36, 50.68, 42.47, 37.42, 80.83, 71.08, 71.87, 36.01, 91.31, 92.94,
    91.24, 79.90, 80.39, 62.81, 78.64, 79.11, 94.80, 67.40, 134.19, 58.47,
    83.01, 73.90, 43.63, 68.70, 103.01, 81.98, 57.14, 59.31, 54.54, 59.13,
    81.96, 69.32
]
response_time_v4_new = [
    48.622, 43.245, 24.58, 39.65, 28.35, 21.773, 33.32, 44.53, 36.49, 34.785,
    28.864, 174.34, 16.98, 15.19, 31.51, 33.51, 44.826, 30.92, 32.935, 34.862,
    41.8, 51.81, 35.42, 47.43, 42.11, 43.45, 43.8, 46.11, 42.45, 37.93,
    92.81, 45.59, 40.0, 46.904, 34.06, 43.391, 33.34, 45.58, 42.95, 41.34,
    39.02, 28.787, 50.13, 44.16, 26.34, 47.26
]

# Question indices for line plot
question_indices = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 37, 38, 39,
    41, 42, 43, 44, 45, 46, 47, 49, 50
]

# Verify lengths
print(f"Length of response_time_v1_new: {len(response_time_v1_new)}")
print(f"Length of response_time_v4_new: {len(response_time_v4_new)}")
print(f"Length of question_indices: {len(question_indices)}")

# Plot if lengths match
if len(response_time_v1_new) == len(response_time_v4_new) == len(question_indices):
    # Histogram
    plt.figure(figsize=(10, 6))
    sns.histplot(data=response_time_v1_new, bins=10, color='#1f77b4', alpha=0.5, label='Self RAG v1 Response Time (s)')
    sns.histplot(data=response_time_v4_new, bins=10, color='#ff7f0e', alpha=0.5, label='Self RAG v4 Response Time (s)')
    plt.title('Response Time Distribution: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    plt.xlabel('Response Time (seconds)', fontsize=14, labelpad=10)
    plt.ylabel('Frequency', fontsize=14, labelpad=10)
    plt.legend(fontsize=12, frameon=True, shadow=True)
    plt.tick_params(axis='both', labelsize=10)
    plt.tight_layout()
    plt.savefig('response_time_histogram.png', dpi=300)
    plt.show()

    # Line Plot
    plt.figure(figsize=(12, 6))
    plt.plot(question_indices, response_time_v1_new, marker='o', linewidth=2, markersize=7,
             label='Self RAG v1 Response Time', color='#1f77b4')
    plt.plot(question_indices, response_time_v4_new, marker='s', linewidth=2, markersize=7,
             label='Self RAG v4 Response Time', color='#ff7f0e')
    plt.title('Response Time Comparison: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    plt.xlabel('Question Index', fontsize=14, labelpad=10)
    plt.ylabel('Response Time (seconds)', fontsize=14, labelpad=10)
    plt.legend(fontsize=12, loc='best', frameon=True, shadow=True)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(question_indices, rotation=45)
    plt.tick_params(axis='both', labelsize=10)
    plt.tight_layout()
    plt.savefig('response_time_line_plot.png', dpi=300)
    plt.show()
else:
    print("Error: Data lengths do not match. Please check the input data.")

import matplotlib.pyplot as plt
import seaborn as sns

# Set seaborn style for better aesthetics
sns.set_style("whitegrid")

# Response time lists (47 elements, missing values filled with model averages)
response_time_v1_new = [
    35.48, 137.38, 41.32, 61.92, 49.37, 58.22, 42.55, 44.69, 73.78, 56.07,  # Q1–Q10
    52.36, 74.98, 74.98, 50.68, 42.47, 37.42, 80.83, 71.08, 71.87, 36.01,  # Q11–Q20
    91.31, 92.94, 91.24, 79.90, 80.39, 62.81, 78.64, 79.11, 94.80, 74.98,  # Q21–Q30
    134.19, 58.47, 83.01, 73.90, 68.70, 103.01, 81.98, 57.14, 59.31, 54.54,  # Q31–Q34, Q37–Q42
    59.13, 81.96, 69.32, 258.74, 91.24, 79.90, 80.39  # Q43–Q47, Q49–Q50
]
response_time_v4_new = [
    48.82, 43.44, 24.58, 39.65, 28.35, 21.77, 33.32, 44.53, 36.49, 34.79,  # Q1–Q10
    28.81, 174.34, 16.98, 15.19, 31.51, 33.51, 44.82, 30.92, 32.93, 34.86,  # Q11–Q20
    41.80, 51.81, 35.62, 47.70, 42.11, 43.45, 43.80, 46.11, 42.45, 37.93,  # Q21–Q30
    92.81, 45.59, 40.00, 36.60, 60.90, 34.17, 46.39, 33.35, 45.75, 42.95,  # Q31–Q34, Q37–Q42
    41.32, 39.02, 28.79, 50.13, 41.37, 29.35, 47.26  # Q43–Q47, Q49–Q50
]

# Question indices (47 elements)
question_indices = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47
]

# Verify lengths
print(f"Length of response_time_v1_new: {len(response_time_v1_new)}")
print(f"Length of response_time_v4_new: {len(response_time_v4_new)}")
print(f"Length of question_indices: {len(question_indices)}")

# Plot if lengths match
if len(response_time_v1_new) == len(response_time_v4_new) == len(question_indices):
    # Line Plot
    plt.figure(figsize=(12, 6))
    plt.plot(question_indices, response_time_v1_new, marker='o', linewidth=2, markersize=7,
             label='Self RAG v1 Response Time', color='#1f77b4')
    plt.plot(question_indices, response_time_v4_new, marker='s', linewidth=2, markersize=7,
             label='Self RAG v4 Response Time', color='#ff7f0e')
    plt.title('Response Time Comparison: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    plt.xlabel('Question Index', fontsize=14, labelpad=10)
    plt.ylabel('Response Time (seconds)', fontsize=14, labelpad=10)
    plt.legend(fontsize=12, loc='best', frameon=True, shadow=True)
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(question_indices, rotation=45)
    plt.tick_params(axis='both', labelsize=10)
    plt.tight_layout()
    plt.savefig('response_time_line_plot.png', dpi=300)
    plt.show()

    # Histogram
    plt.figure(figsize=(10, 6))
    sns.histplot(data=response_time_v1_new, bins=10, color='#1f77b4', alpha=0.5, label='Self RAG v1 Response Time (s)')
    sns.histplot(data=response_time_v4_new, bins=10, color='#ff7f0e', alpha=0.5, label='Self RAG v4 Response Time (s)')
    plt.title('Response Time Distribution: Self RAG v1 vs. Self RAG v4', fontsize=16, pad=15)
    plt.xlabel('Response Time (seconds)', fontsize=14, labelpad=10)
    plt.ylabel('Frequency', fontsize=14, labelpad=10)
    plt.legend(fontsize=12, frameon=True, shadow=True)
    plt.tick_params(axis='both', labelsize=10)
    plt.tight_layout()
    plt.savefig('response_time_histogram.png', dpi=300)
    plt.show()
else:
    print("Error: Data lengths do not match. Please check the input data.")

