# -*- coding: utf-8 -*-
"""Self_RAG_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdFrlNb8jDwtOchI9mFBkFWs5KSeGxiP
"""

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries
!pip install langchain
# %pip install -qU langchain_community
# %pip install pypdf
!pip install langchain-experimental
!pip install faiss-cpu
# %pip install -U transformers accelerate
!pip install -U langchain-huggingface
!pip install -q langchain langchain-community pypdf transformers #accelerate
# %pip install -qU langchain-groq
# %pip install -qU langchain-groqpip install -U langchain-nomic langchain_community tiktoken langchainhub  langchain langgraph nomic[local]
!pip install -U --quiet langgraph langchain-text-splitters
!pip install pinecone-client
!pip install langchain_pinecone
!pip install bert-score python-docx
!pip install rank_bm25
!pip install flashrank

import os
import getpass
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain.chat_models import init_chat_model
from langgraph.graph import END, StateGraph, START
from typing import List
from typing_extensions import TypedDict
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from pprint import pprint
import time
from bert_score import score
from docx import Document
from langchain_experimental.text_splitter import SemanticChunker
from google.colab import files
import re
from flashrank import Ranker
from langchain_pinecone import PineconeVectorStore

# Import the PyPDF loader from langchain_community
from langchain_community.document_loaders import PyPDFDirectoryLoader
# Define a function to load all PDF documents from a directory
def load_documents(data_path):
    return PyPDFDirectoryLoader(data_path).load()

# Define the path to the directory containing the PDF files and loading the PDF documents
pdfs_path="/content/drive/MyDrive/Deep_Dataset"
pdfs=load_documents(pdfs_path)

# Loading a pre-trained sentence embedding model from HuggingFace
embedding_model = HuggingFaceEmbeddings(
    model_name="Qwen/Qwen3-Embedding-0.6B",
    model_kwargs={"trust_remote_code": True},
    encode_kwargs={"normalize_embeddings": True}
)
# Initialize=ing the text splitter to create overlapping chunks
text_splitter = SemanticChunker(embedding_model, breakpoint_threshold_type="interquartile", breakpoint_threshold_amount=1.5)
# Splitting the loaded PDF documents into manageable text chunks
splits = text_splitter.split_documents(documents=pdfs)

os.environ["GROQ_API_KEY"] = "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"
os.environ['PINECONE_API_KEY'] = 'pcsk_5zeWzV_Fq4aaDWo3nt42zHfnbc2cDomU3yyftv43WbJerx5fEjrsvRSiqb8CYYjgTK6FQ6'

from pinecone import Pinecone

pc = Pinecone(api_key="pcsk_5zeWzV_Fq4aaDWo3nt42zHfnbc2cDomU3yyftv43WbJerx5fEjrsvRSiqb8CYYjgTK6FQ6")
index = "rag-policy"

vectordb = PineconeVectorStore.from_documents(splits,index_name="rag-policy",embedding=embedding_model)

from sentence_transformers import CrossEncoder
# Initialize Groq LLM for generation
model = init_chat_model("groq:meta-llama/llama-4-maverick-17b-128e-instruct",temperature=0.4,max_tokens=512,timeout=None)
retriever = vectordb.as_retriever(search_kwargs={"k": 8})
# Initialize FlashRank reranker
reranker_model = Ranker(model_name="ms-marco-MiniLM-L-12-v2")

# RAG prompt for answer generation
template = (
    "You are an assistant for question-answering tasks regarding NACCAS policies. "
    "Use the following pieces of retrieved context to answer the question. "
    "If you don't know the answer, just say that you don't know. "
    "Use 25 sentences maximum and keep the answer concise.\n"
    "Question: {question} \n"
    "Context: {context}"
)
prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = prompt | model | StrOutputParser()

# Question re-writer
re_write_prompt = PromptTemplate(
    template="""You are a question re-writer that converts an input question to a better version optimized for vectorstore retrieval.
    Look at the initial and formulate an improved question.
    Here is the initial question: \n\n {question}. Improved question with no preamble: \n """,
    input_variables=["question"],
)
question_rewriter = re_write_prompt | model | StrOutputParser()

from typing import List, TypedDict
from langchain.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from sklearn.metrics.pairwise import cosine_similarity
from flashrank import Ranker, RerankRequest

# Define graph state
class GraphState(TypedDict):
    question: str
    generation: str
    documents: List[str]

# --- Graph Nodes ---

def retrieve(state):
    print("---RETRIEVE---")
    question = state["question"]
    documents = retriever.get_relevant_documents(question)
    return {"documents": documents, "question": question}

def rerank_documents(state, top_k=4):
    try:
        print("---RERANK DOCUMENTS (FLASHRANK)---")
        question = state["question"]
        documents = state["documents"]

        # Initialize FlashRank reranker
        reranker_model = Ranker(model_name="ms-marco-MiniLM-L-12-v2")

        # Format documents for FlashRank (requires list of dicts with 'text' and 'id')
        passages = [
            {"id": idx, "text": doc.page_content}
            for idx, doc in enumerate(documents)
        ]

        # Create RerankRequest
        rerank_request = RerankRequest(query=question, passages=passages)

        # Rerank documents
        rerank_results = reranker_model.rerank(rerank_request)

        # Select top-k documents based on reranking scores
        top_docs = []
        for result in rerank_results[:top_k]:
            doc_idx = result["id"]
            score = result["score"]
            doc = documents[doc_idx]
            top_docs.append(doc)
            print(f"Doc {doc_idx+1} (Original Rank) → Score: {score:.4f}")

        return {"documents": top_docs, "question": question}

    except Exception as e:
        logger.error("Error during reranking: %s", str(e))
        return {"documents": documents[:top_k], "question": question}


def generate(state):
    print("---GENERATE---")
    question = state["question"]
    documents = state["documents"]
    generation = rag_chain.invoke({"context": format_docs(documents), "question": question})
    return {"documents": documents, "question": question, "generation": generation}

def transform_query(state):
    print("---TRANSFORM QUERY---")
    question = state["question"]
    documents = state["documents"]
    better_question = question_rewriter.invoke({"question": question})
    return {"documents": documents, "question": better_question}

# --- Graph Edges (Control Flow) ---

def decide_to_generate(state):                       # modified
    print("---ASSESS RERANKED DOCUMENTS---")
    filtered_documents = state["documents"]
    if not filtered_documents:
        print("---DECISION: NO DOCUMENTS REMAIN, TRANSFORM QUERY---")
        return "transform_query"
    else:
        print("---DECISION: RERANKED DOCUMENTS AVAILABLE, GENERATE---")
        return "generate"


def grade_generation_v_documents_and_question(state, similarity_threshold=0.5):
    print("---CHECK HALLUCINATIONS (COSINE SIMILARITY)---")
    question = state["question"]
    documents = state["documents"]
    generation = state["generation"]

    generation_embedding = embedding_model.embed_query(generation)
    doc_embeddings = [embedding_model.embed_query(doc.page_content) for doc in documents]
    similarities = [cosine_similarity([generation_embedding], [doc_emb])[0][0] for doc_emb in doc_embeddings]
    max_similarity = max(similarities) if similarities else 0.0
    print(f"→ MAX DOC SIMILARITY: {max_similarity:.4f}")

    if max_similarity >= similarity_threshold:
        print("→ GENERATION IS GROUNDED")
        query_embedding = embedding_model.embed_query(question)
        answer_similarity = cosine_similarity([generation_embedding], [query_embedding])[0][0]
        print(f"→ ANSWER SIMILARITY: {answer_similarity:.4f}")
        return "useful" if answer_similarity >= similarity_threshold else "not useful"
    else:
        print("→ GENERATION NOT GROUNDED, RE-TRY")
        return "not supported"

# Build graph
workflow = StateGraph(GraphState)

# Add nodes
workflow.add_node("retrieve", retrieve)
workflow.add_node("rerank_documents", rerank_documents)
workflow.add_node("generate", generate)
workflow.add_node("transform_query", transform_query)

# Define edges
workflow.add_edge(START, "retrieve")
workflow.add_edge("retrieve", "rerank_documents")

# Skip grading; decide after rerank whether to generate or rewrite
workflow.add_conditional_edges(
    "rerank_documents",
    decide_to_generate,  # This now checks if reranked docs exist
    {
        "transform_query": "transform_query",
        "generate": "generate"
    },
)

# Retry from transformed query
workflow.add_edge("transform_query", "retrieve")

# Decide if the generation is valid or retry
workflow.add_conditional_edges(
    "generate",
    grade_generation_v_documents_and_question,
    {
        "not supported": "generate",
        "useful": END,
        "not useful": "transform_query"
    },
)

# Compile graph
app = workflow.compile()

#from time import time
import ast

# Extract questions and ground truths from uploaded .txt file
def extract_qas_from_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract Python list-style variables using ast.literal_eval
    questions_block = content.split("questions =")[1].split("ground_truths =")[0].strip()
    truths_block = content.split("ground_truths =")[1].strip()

    questions = ast.literal_eval(questions_block)
    ground_truths = ast.literal_eval(truths_block)

    return questions, ground_truths

# Setting the uploaded .txt file path
doc_path = "/content/drive/MyDrive/naccas questions and ground-truths.txt"

# Load questions and truths
questions, ground_truths = extract_qas_from_txt(doc_path)
print(f"Extracted {len(questions)} questions and {len(ground_truths)} ground truths.")

# Run evaluation
output_path = "/content/selfrag_qwen3_reranker.txt"
with open(output_path, "w", encoding="utf-8") as f:
    for i, (q, gt) in enumerate(zip(questions, ground_truths), 1):
        try:
            inputs = {"question": q}
            start = time.time()
            for output in app.stream(inputs, {"recursion_limit": 15}):
                for _, value in output.items():
                    pass
            response = value["generation"]
            end = time.time()
            P, R, F1 = score([response], [gt], lang="en")
            p, r, f1_score = P.item(), R.item(), F1.item()
            f.write(f"Q{i}: {q}\nResponse: {response}\nGround Truth: {gt}\n")
            f.write(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}\n")
            f.write(f"Time: {end - start:.2f} sec\n{'-'*80}\n")
            print(f"\nQ{i}: {q}")
            print(f"Response: {response}")
            print(f"Ground Truth: {gt}")
            print(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}")
            print(f"Time: {end - start:.2f} sec")
            print("-" * 80)
        except Exception as e:
            print(f"\nQ{i}: {q}\n[Error during processing: {e}]")
            print("---" * 80 + "\n")
            f.write(f"Q{i}: {q}\n[Error during processing: {e}]\n{'-'*80}\n")
            continue

files.download(output_path)