# -*- coding: utf-8 -*-
"""Self_RAG_Experimentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-C_OG_Hnm4I5mw070gkaY_sWW8Nh_rgs
"""

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries
# %pip install langchain
# %pip install -qU langchain_community
# %pip install pypdf
!pip install faiss-cpu
#%pip install -U bitsandbytes
# %pip install -U transformers accelerate
!pip install -U langchain-huggingface
# === INSTALLS ===
!pip install -q langchain langchain-community pypdf transformers #accelerate
# %pip install -qU langchain-groq
# %pip install -qU langchain-groqpip install -U langchain-nomic langchain_community tiktoken langchainhub  langchain langgraph nomic[local]
#from transformers import BitsAndBytesConfig
!pip install -U --quiet langgraph langchain-text-splitters
#!pip install ragas
#!pip install git+https://github.com/explodinggradients/ragas.git
!pip install sacrebleu
!pip install bert-score python-docx

import os
import getpass
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import PyPDFDirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.prompts import PromptTemplate
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain.chat_models import init_chat_model
from langgraph.graph import END, StateGraph, START
from typing import List
from typing_extensions import TypedDict
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from pprint import pprint
import time
from bert_score import score
from docx import Document
from google.colab import files
import re

# Import the PyPDF loader from langchain_community
from langchain_community.document_loaders import PyPDFDirectoryLoader
# Define a function to load all PDF documents from a directory
def load_documents(data_path):
    return PyPDFDirectoryLoader(data_path).load()

# Define the path to the directory containing the PDF files and loading the PDF documents
pdfs_path="/content/drive/MyDrive/Deep_Dataset"
pdfs=load_documents(pdfs_path)

# from langchain.text_splitter import RecursiveCharacterTextSplitter
# Initialize=ing the text splitter to create overlapping chunks
#text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
# # Splitting the loaded PDF documents into manageable text chunks
#splits = text_splitter.split_documents(documents=pdfs)
# Loading a pre-trained sentence embedding model from HuggingFace
embedding_model = HuggingFaceEmbeddings(
    model_name="Qwen/Qwen3-Embedding-0.6B",
    model_kwargs={"trust_remote_code": True},
    encode_kwargs={"normalize_embeddings": True}
)
# Creating a FAISS based vector store from the text chunks using the embedding model
#vectordb = FAISS.from_documents(splits, embedding_model) #Faiss is indexing the vectors created from wordembeddings, also note that embeddings are also created from splits in this step

# # Save the FAISS index to Google Drive (or any directory)
# vectordb.save_local("/content/drive/MyDrive/Qwen3Embeddings")

# from langchain.vectorstores import FAISS

# Safely load your trusted FAISS index from local/Drive
vectordb = FAISS.load_local("/content/drive/MyDrive/Qwen3Embeddings", embeddings=embedding_model,allow_dangerous_deserialization=True)
# # Here deserialization means to convert a stored object (e.g in pickle format) to python code, which can be dangerous if file is from untrusted source

#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

if "GROQ_API_KEY" not in os.environ:
     os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

# Initialize Groq LLM for generation
model = init_chat_model("groq:meta-llama/llama-4-maverick-17b-128e-instruct",temperature=0.5,max_tokens=512,timeout=None)

retriever=vectordb.as_retriever()

# RAG prompt for answer generation
template = (
    "You are an assistant for question-answering tasks regarding NACCAS policies. "
    "Use the following pieces of retrieved context to answer the question. "
    "If you don't know the answer, just say that you don't know. "
    "Use 25 sentences maximum and keep the answer concise.\n"
    "Question: {question} \n"
    "Context: {context}"
)
prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = prompt | model | StrOutputParser()

# Question re-writer
re_write_prompt = PromptTemplate(
    template="""You are a question re-writer that converts an input question to a better version optimized for vectorstore retrieval.
    Look at the initial and formulate an improved question.
    Here is the initial question: \n\n {question}. Improved question with no preamble: \n """,
    input_variables=["question"],
)
question_rewriter = re_write_prompt | model | StrOutputParser()

# Define graph state
class GraphState(TypedDict):
    question: str
    generation: str
    documents: List[str]

# Graph nodes
def retrieve(state):
    print("---RETRIEVE---")
    question = state["question"]
    documents = retriever.get_relevant_documents(question)
    return {"documents": documents, "question": question}

def generate(state):
    print("---GENERATE---")
    question = state["question"]
    documents = state["documents"]
    generation = rag_chain.invoke({"context": format_docs(documents), "question": question})
    return {"documents": documents, "question": question, "generation": generation}

def grade_documents(state, similarity_threshold=0.5):
    print("---CHECK DOCUMENT RELEVANCE TO QUESTION (COSINE SIMILARITY)---")
    question = state["question"]
    documents = state["documents"]
    query_embedding = embedding_model.embed_query(question)
    filtered_docs = []
    for d in documents:
        doc_embedding = embedding_model.embed_query(d.page_content)
        similarity = cosine_similarity([query_embedding], [doc_embedding])[0][0]
        print(f"---DOCUMENT SIMILARITY SCORE: {similarity:.4f}---")
        if similarity >= similarity_threshold:
            print("---GRADE: DOCUMENT RELEVANT---")
            filtered_docs.append(d)
        else:
            print("---GRADE: DOCUMENT NOT RELEVANT---")
    return {"documents": filtered_docs, "question": question}

def transform_query(state):
    print("---TRANSFORM QUERY---")
    question = state["question"]
    documents = state["documents"]
    better_question = question_rewriter.invoke({"question": question})
    return {"documents": documents, "question": better_question}

# Graph edges
def decide_to_generate(state):
    print("---ASSESS GRADED DOCUMENTS---")
    filtered_documents = state["documents"]
    if not filtered_documents:
        print("---DECISION: ALL DOCUMENTS ARE NOT RELEVANT, TRANSFORM QUERY---")
        return "transform_query"
    else:
        print("---DECISION: GENERATE---")
        return "generate"

def grade_generation_v_documents_and_question(state, similarity_threshold=0.5):
    print("---CHECK HALLUCINATIONS (COSINE SIMILARITY)---")
    question = state["question"]
    documents = state["documents"]
    generation = state["generation"]

    # Hallucination check: compare generation embedding to document embeddings
    generation_embedding = embedding_model.embed_query(generation)
    doc_embeddings = [embedding_model.embed_query(doc.page_content) for doc in documents]
    similarities = [cosine_similarity([generation_embedding], [doc_emb])[0][0] for doc_emb in doc_embeddings]
    max_similarity = max(similarities) if similarities else 0.0
    print(f"---HALLUCINATION SIMILARITY SCORE: {max_similarity:.4f}---")

    if max_similarity >= similarity_threshold:
        print("---DECISION: GENERATION IS GROUNDED IN DOCUMENTS---")
        # Answer relevance check: compare generation embedding to query embedding
        print("---GRADE GENERATION vs QUESTION (COSINE SIMILARITY)---")
        query_embedding = embedding_model.embed_query(question)
        answer_similarity = cosine_similarity([generation_embedding], [query_embedding])[0][0]
        print(f"---ANSWER SIMILARITY SCORE: {answer_similarity:.4f}---")
        if answer_similarity >= similarity_threshold:
            print("---DECISION: GENERATION ADDRESSES QUESTION---")
            return "useful"
        else:
            print("---DECISION: GENERATION DOES NOT ADDRESS QUESTION---")
            return "not useful"
    else:
        print("---DECISION: GENERATION IS NOT GROUNDED IN DOCUMENTS, RE-TRY---")
        return "not supported"

# Build graph
workflow = StateGraph(GraphState)
workflow.add_node("retrieve", retrieve)
workflow.add_node("grade_documents", grade_documents)
workflow.add_node("generate", generate)
workflow.add_node("transform_query", transform_query)
workflow.add_edge(START, "retrieve")
workflow.add_edge("retrieve", "grade_documents")
workflow.add_conditional_edges(
    "grade_documents",
    decide_to_generate,
    {"transform_query": "transform_query", "generate": "generate"},
)
workflow.add_edge("transform_query", "retrieve")
workflow.add_conditional_edges(
    "generate",
    grade_generation_v_documents_and_question,
    {"not supported": "generate", "useful": END, "not useful": "transform_query"},
)

# Compile graph
app = workflow.compile()

# Evaluation function
def extract_qas(path):
    doc = Document(path)
    questions, truths = [], []
    q, t, mode = "", "", None
    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue
        match = re.match(r'^(\d+)[\.\)]?\s*(.+)', text)
        if match:
            if q and t:
                questions.append(q.strip())
                truths.append(t.strip())
            q = match.group(2).strip()
            t, mode = "", None
        elif text.lower().startswith("ground truth"):
            mode = "truth"
        elif mode == "truth":
            t += " " + text.strip()
    if q and t:
        questions.append(q.strip())
        truths.append(t.strip())
    return questions, truths

# Run evaluation
docx_path = "/content/drive/MyDrive/model Generated Response and Scores(1).docx"
questions, ground_truths = extract_qas(docx_path)
print(f"Extracted {len(questions)} QAs.")

output_path = "/content/selfrag_qwen3_results.txt"
with open(output_path, "w", encoding="utf-8") as f:
    for i, (q, gt) in enumerate(zip(questions, ground_truths), 1):
        try:
            inputs = {"question": q}
            start = time.time()
            for output in app.stream(inputs, {"recursion_limit": 5}):
                for _, value in output.items():
                    pass
            response = value["generation"]
            end = time.time()
            P, R, F1 = score([response], [gt], lang="en")
            p, r, f1_score = P.item(), R.item(), F1.item()
            f.write(f"Q{i}: {q}\nResponse: {response}\nGround Truth: {gt}\n")
            f.write(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}\n")
            f.write(f"Time: {end - start:.2f} sec\n{'-'*80}\n")
            print(f"\nQ{i}: {q}")
            print(f"Response: {response}")
            print(f"Ground Truth: {gt}")
            print(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}")
            print(f"Time: {end - start:.2f} sec")
            print("-" * 80)
        except Exception as e:
            print(f"\nQ{i}: {q}\n[Error during processing: {e}]")
            print("---" * 80 + "\n")
            f.write(f"Q{i}: {q}\n[Error during processing: {e}]\n{'-'*80}\n")
            continue

files.download(output_path)

# from bert_score import score
# from time import time
# from google.colab import files

# # Pre-defined lists of questions and ground truths from the document
# questions = [
#     "What is the refund policy?",
#     "What if one catalog used for several institutions/Instructions regarding using other institute catalog?",
#     "Who qualifies as ATB(ability to benefit)?",
#     "What would be the catalog requirement / what should be the requirements of the check list of the institute?",
#     "Which components must include in distant policy or for institutes that provide distant education?",
#     "On which things the curriculum of cosmetology based on?",
#     "What should be the curriculum of the instructor trainer?",
#     "What should be the substantive interaction for the distant education learning activities?",
#     "What are the Requirements for Institutions that have Undergone a Disaster?",
#     "If institute is being harmed by any natural disaster what thing should should be notify to NACCAS?",
#     "What are the exceptions for the instructor qualifications?",
#     "What factors would be considered by institute for teacher student ratio?",
#     "What does the collection policy requires?",
#     "Can a institute charge the student for extra instructional charges what are there rules?",
#     "What does the Internal Grievance Procedure Policy require from the institute?",
#     "What is Teach-Out Policy in accordance with policy in accordance to iv.05 policy?",
#     "What is the submission requirements of the Teach out policy?",
#     "What is leave of absence policy (LOA)?",
#     "What are the requirements of LOA?",
#     "What is Definition of an Ability-to-Benefit Student?",
#     "A school applying for NACCAS accreditation wants to advertise its status. Can it claim to be accredited by NACCAS or use the phrase candidate for accreditation in its promotional materials? Explain the policy's stance.",
#     "A school named Global Academy of Cosmetology and Massage wants to use Global Academy on its exterior signage and GAC in its social media advertising. Is this permissible under the NACCAS policy? Provide details to support your answer.",
#     "A school wishes to advertise a new pilot program called 'Advanced Esthetics' that has not yet been approved by NACCAS. What specific requirements must the school follow to comply with the policy when advertising this program?",
#     "Can a school named 'Elite Beauty Institute, LLC' use its full name, including 'LLC,' in its advertising materials? Why or why not?",
#     "A school that advertises that 90% of our graduates are employed within six months of graduation in its promotional brochure must have verifiable documentation to substantiate the claim and ensure that the data is current accurate and based on the NACCAS definition of placement the school must also be able to provide this documentation to NACCAS upon request to ensure compliance with advertising standards?",
#     "A prospective student wishes to enroll in a cosmetology program at a NACCAS-accredited school. They provide a transcript showing completion of a two-year associate’s degree program. Does this satisfy the educational requirements for admission, and what documentation must the school maintain?",
#     "A homeschooled student applies to a NACCAS-accredited school in a state that issues a secondary school completion credential for homeschoolers. What must the student provide to be eligible for enrollment, and what additional condition must the school meet?",
#     "Can a student who is still enrolled in high school enroll in an associate’s degree program at a NACCAS-accredited institution without a high school diploma? Why or why not?",
#     "A school accepts ability-to-benefit (ATB) students and uses a third-party test to assess their eligibility. What documentation must the school maintain for these students, and what alternative option does the policy provide for ATB students?",
#     "A student enrolls in a NACCAS-accredited school under a training agreement with a government agency. The agreement specifies certain admission requirements that differ from the school’s standard policy. How should the school handle this student’s admission, and what documentation is required?",
#     "An ATB student completes a 1000-hour program at a NACCAS-accredited school in 2023, having demonstrated their ability to benefit by completing 225 clock hours after enrollment. By what year must the school retain the student’s ATB-related records, and what specific records are required?",
#     "A NACCAS-accredited school admits an ATB student into a 500-hour program without requiring a test or post-enrollment completion of 6 credit hours or 225 clock hours. Does this comply with the NACCAS Ability-to-Benefit Policy, and why or why not?",
#     "An institution collects a $200 registration fee from an applicant before providing an enrollment agreement. Does this comply with the NACCAS Enrollment Agreement Requirements policy, and why or why not?",
#     "A NACCAS-accredited institution submits an enrollment agreement to the Commission as part of its Institutional Self-Study (ISS). What additional document must accompany the enrollment agreement, and what is its purpose?",
#     "An institution hires an instructor for an occupational associate degree program who lacks an associate degree but provides letters of recommendation from a former employer. The institution does not retain these letters for review. The program includes a syllabus missing the date of last review, and the externship agreement lacks evaluation criteria. Does this comply with the NACCAS Policy on Occupational Associate Degree Programs, and why or why not?",
#     "What are the minimum requirements for a course syllabus in an occupational associate degree program, according to the NACCAS Policy on Occupational Associate Degree Programs?",
#     "A NACCAS-accredited institution offers a 900-clock-hour occupational associate degree program in esthetics, including 300 hours of lecture, 300 hours of lab, and 300 hours of clinical work. How many semester credit hours would this program equate to, according to the clock-to-credit hour conversion in the NACCAS policy?",
#     "What financial and enrollment information must an institution include in its disaster recovery plan under the NACCAS Policy on Disasters?",
#     "A NACCAS-accredited institution’s campus is severely damaged by a hurricane, forcing it to cease teaching for two weeks, which is not listed in the catalog. What must the institution do to comply with the NACCAS Policy on Disasters, and to whom should it send the notification?",
#     "A student requires extra instruction due to excessive absences but has not yet reached the completion date on their enrollment agreement. The institution charges the student for these hours and records the payment. What additional step must the institution take to comply with the NACCAS Policy on Extra Instructional Charges?",
#     "A student in a 600-hour cosmetology program has exhausted all allowed absences within the contract period and requires an additional 30 hours of instruction to complete the program. The enrollment agreement specifies a charge of $10 per clock hour for extra instruction. Can the institution charge the student for these hours, and what must it ensure regarding the charges?",
#     "A student enrolls in a 600-hour cosmetology program at a NACCAS-accredited institution in a state with no mandated refund policy. The student withdraws after completing 60 hours (10% of the program). According to the NACCAS Minimum Tuition Adjustment Schedule, what percentage of the total tuition does the student owe, and within what timeframe must the refund be issued?",
#     "An institution offers an Electrology program in a state without mandated content. What must the curriculum include to comply with the NACCAS Minimum Curriculum Requirements Policy?",
#     "A NACCAS-accredited institution offers a Hairdressing-only program in a state with no mandated curriculum content. What components of the Cosmetology curriculum can the institution exclude, and what must it still include?",
#     "In the absence of state-mandated content, what curriculum components must an institution include for a Cosmetology program, according to the NACCAS Minimum Curriculum Requirements Policy?",
#     "A NACCAS-accredited institution offers a 600-hour cosmetology program with 200 hours delivered via synchronous distance education. What must the institution ensure regarding substantive and regular interaction between students and instructors in this program?",
#     "A NACCAS-accredited institution offers a 1000-hour cosmetology program and wants to include a state-authorized externship course. A student is selected for the externship at a licensed salon. What criteria must the institution use to select the student, and what examination must the student have completed?",
#     "A student at a NACCAS-accredited institution wishes to file a formal grievance about an instructor’s conduct. The institution has a written grievance policy, but the student is unaware of it because it was not communicated at the program’s start. The institution provides complaint forms only upon request. Does this comply with the NACCAS Internal Grievance Procedure Policy, and what steps should the institution take to address the situation?",
#     "A full-time student in a 48-credit-hour esthetics program (two 24-credit-hour terms) fails to achieve a 70% cumulative grade average at the midpoint of the first term (12 credit hours). The institution participates in Title IV programs and allows appeals for SAP determinations. What steps must the institution take, and what must its SAP policy include regarding the appeal process?",
#     "A full-time student in a 1500-hour esthetics program (academic year of 900 clock hours, 30 weeks) fails to meet the minimum 70% cumulative grade average at the second evaluation period (900 clock hours, 30 weeks). The institution allows appeals for SAP determinations. What steps must the institution take, and what must its SAP policy include regarding the appeal process?"
# ]

# ground_truths = [
#     "Refund policy must comply with the NACCAS Withdrawal and Settlement Policy and Checklist and state or federal mandated policies.",
#     "All institutions that use a common catalog must be of common ownership and this must be indicated. Any pictures of the physical facilities must be captioned to identify the particular institution depicted. The members of the headquarters administration who have supervisory responsibilities for the institutions must be clearly identified. Any information contained in the catalog that is not common to all institutions must be clearly identified and separated by state, subject, and program, to include all policies, disclosures, etc. The names and addresses of the institutions which utilize the catalog must be Included.",
#     "A student without a high school diploma or equivalent who is beyond compulsory school age and has the capacity to benefit from vocational education or training. Following are the Institutional Responsibility that must be acquire for ATB: Schools must develop, publish, and follow a policy on ATB students. This ATB policy must appear in the school catalog. If a school does not admit ATB students, this must also be clearly stated. Temporary methods (like paste-overs or inserts) are allowed until the next full catalog update.",
#     "The institution provides detailed information for prospective students, including its name, address, date of publication, and mission statement, clearly outlining its commitment to educational excellence. Admissions details specify program-specific requirements, including the Ability-to-Benefit (ATB) statement in compliance with Policy IV.02, along with comprehensive transfer and re-entry policies. Each program outline includes the program name, objectives, content, grading criteria, and class schedules. Institutional details cover the available facilities, graduation requirements, certifications awarded upon completion, refund policies, job assistance services, academic calendar, and a firm non-discrimination policy. Legal and policy information encompasses student rights, privacy practices, scholarship availability, affiliations with licensing or accrediting bodies, and any additional information that may affect a student’s decision to enroll. Regulations and costs are clearly defined, including rules for attendance and conduct, tuition and fee structures, book and supply costs, payment methods, and procedures for verifying student identity in distance learning scenarios. If the catalog includes inserts or multiple pages, they are consecutively numbered and referenced in the Table of Contents, and content specific to individual campus locations is distinctly labeled to avoid confusion.",
#     "Institutions offering distance education must have a formal policy that complies with local, state, and federal laws, as well as NACCAS Standards and Criteria. The policy must include the following key components:1. Restriction on Clinical Instruction  Practical training involving live models/clients cannot be delivered via distance education. 2. Interaction Requirements:Distance education (whether synchronous or asynchronous) must include substantive and regular interaction between students and instructors. Substantive interaction must involve at least two of the following: Direct instruction: Assessment or feedback on coursework Answering content-related questions. Facilitating content discussions Regular interaction must include: Scheduled opportunities for interaction Monitoring student engagement and instructor accountability For asynchronous delivery, student “seat time” must be validated for clock hour programs.3. Monthly On-Campus Assessments At least once per month, student performance for distance education must be assessed on-campus by a qualified instructor. 4. Final Exams:Upon completing the program, students must pass an on-campus comprehensive Academic and Practical final exam to meet curriculum and state licensure requirements. 5. Transcript Notation: Transcripts and academic records must clearly indicate any distance education Components.6. Licensure Disclaimer: Before enrollment, students must sign a disclosure warning that distance education credits may not be recognized for licensure or reciprocity in other states.This policy ensures that distance education maintains instructional integrity,transparency, and regulatory compliance.",
#     "1.Sciences: Infection control, chemistry, electricity, anatomy, hair/skin/nail disorders. 2. Hair Techniques: Styling, shaping, coloring, texture services, treatments, shampooing. 3. Skin (if applicable): Skin care, makeup, hair removal, contraindications. 4. Nails (if applicable): Manicure, pedicure, artificial nails. 5. Career Info: Ethics, communication, compensation, income, licensing, laws, business, record keeping.",
#     "1. Teaching Principles: Classroom management, methods. 2. Course Development: Lesson planning, AV aids, test development/evaluation. 3. Advising: Feedback delivery, improvement plans. 4. Career Info: Ethics, communication, licensing, laws, record keeping. This curriculum ensures that students receive comprehensive, standardized training across various disciplines, while also preparing them for career success and licensure.",
#     "Substantive interaction for distance education learning activities is engaging students in teaching, learning, and assessment and must include two (2) of the following at a minimum: i. Providing direct instruction ii. Assessing or providing feedback on students distance education coursework iii. Providing information or responding to questions about the content of distance education coursework iv. Facilitating a group discussion regarding the content of distance education coursework",
#     "In the event of a disaster that renders an institution non-compliant at its approved location, the institution must submit a comprehensive written plan to NACCAS within 30 calendar days, detailing how it will resume operations and regain compliance. This plan must include a thorough explanation of the disaster, intentions regarding the facility whether returning to the original location or relocating permanently and, if applicable, a timeline for return or a change of location application. If there are changes in administrative or instructional staff, an organizational chart, job descriptions, and reporting lines must be included. The institution must also describe its ongoing reporting practices (e.g., attendance, enrollment, academic status), how student records from the affected location will be preserved, and provide enrollment figures before and after the disaster, along with projections. A detailed, to-scale floor plan of the current facility, evidence of safe occupancy, and valid state permits to operate are required. A financial plan outlining projected revenues, expenses, startup costs, staffing needs, and expected income from enrollments and clinic services must be submitted. Additionally, the plan must list all courses or programs to be offered during the recovery period and present a timeline for achieving full compliance with NACCAS Standards, including the operational requirement under Section 1.2. Finally, the institution’s business plan will be reviewed by the NACCAS Executive Director, who may request further information necessary for Commission evaluation.",
#     "You must notify NACCAS immediately should the following occur: 1. The school or a significant part of its facilities have been destroyed. 2. You have ceased teaching students for any days not listed in your catalog. 3. There are circumstances that might affect your ability to comply with accreditation standards or procedures. 4. If the institution is unable to come into full compliance at its approved location within thirty (30) calendar days, it must provide a written plan and timeline, stating how it plans to resume operations.",
#     "Exceptions to the associates degree requirement may be justified for instructors who have demonstrable current exceptional professional certification(s), letters of recommendation or attestations from previous employer(s), letters attesting to this expertise from professional peers not connected to the college, real examples of previous success in the field such as published work, juried exhibits and shows, evidence of a professional portfolio accepted by the institution and available for review, and/or other significant documented experience relevant to the courses to be taught.",
#     "The institution shall consider the following factors in determining the student/teacher ratio: 1. The amount of lecture given by instructors in skill building and practice classes; 2. The level of existing skills of the student; 3. The amount of direct supervision exercised by the instructor and the availability of instructional equipment in the lab setting where there is primary instruction in a specific skill; and 4. The use of technology in providing alternative instruction or evaluation",
#     "26. Collection procedures shall reflect ethical business practices. 27. The name of the National Accrediting Commission of Career Arts and Sciences is not used in the institution's refund policy nor in any of its collection efforts. 28. Collection correspondence regarding cancellation and settlement from the institution itself, banks, collection agencies, lawyers, or any other third parties representing the institution clearly acknowledges the existence of the Withdrawal and Settlement Policy. 29. If promissory notes or contracts for tuition are sold or discounted to third parties, the third party must comply with the cancellation and settlement policy of the institution",
#     "An institution may charge a student for extra instruction needed to complete his/her program under the following conditions: 1. The absences allowed within the contract period have been exhausted; and 2. The amount charged per unit of instruction (i.e., clock hour, week, credit or competency) is clearly stated on the enrollment agreement and tuition and fees information is provided to students upon enrollment. Schools charging a fee prior to the completion date appearing on the enrollment agreement have secured from the student an acknowledgment of credit to their account. All monies received for extra instruction prior to completion of the student contract are refunded if the student terminates.",
#     ": At a minimum: a. The policy must be written and identified as a complaint or grievance policy. b. Students must be informed of the policy at the beginning of the course or program. c. The policy must clearly define the steps a student must take to file a formal grievance. d. Forms for filing a complaint are made available to students. Records of complaints and their resolution, as applicable, are retained according to the school?s record keeping policy for review by the NACCAS on-site visit team. The school may not require a student to exercise or exhaust his or her rights under the school?s grievance procedure before filing a complaint with NACCAS or another regulatory body if such requirement violates applicable laws or regulations. The school may refer to the NACCAS Sample Forms and Guidelines for guidance in developing a policy appropriate for the school.",
#     "1. A Closure includes any change of location considered by the U.S. Department of Education to be a closure of the existing Institution; and 2. In general, the Commission considers a Teach-Out Agreement to be practicable unless the Institution submitting a Teach-Out Plan can demonstrate that there are no Institutions within a 50-mile radius that (i) meet the requirements of Checklist Items 7 and 8 of this Policy and (ii) are willing to enter into a Teach-Out Agreement meeting the requirements of Checklist Items 4 and 5 of this Policy.",
#     "All accredited and candidate institutions must submit a Teach-Out Plan, including a draft Teach-Out Agreement if practicable, with each application for accreditation, renewal, and annual report submission, as required by NACCAS policy. In the event of a Teach-Out Event—such as a program or institutional closure—a Teach-Out Plan must be submitted within 15 days of the event if unplanned, or 30 days prior if planned. The plan must include a draft or executed Teach-Out Agreement and, when applicable, a list of accredited schools within a 50-mile radius that meet specific checklist requirements (Items 7 and 8). A Teach-Out Agreement is considered practicable unless the institution can prove there are no qualifying institutions within this radius. Importantly, issuing pro rata refunds to students does not replace the requirement to submit a Teach-Out Plan and Agreement. When a Teach-Out Agreement involves a program accredited by another recognized accrediting agency, NACCAS will notify that agency upon approval of the agreement.",
#     "A authorized leave of absence (LOA) is a temporary interruption in a student?s program of study. LOA refers to the specific time period during a program when a student is not in attendance. A LOA is not required if a student is not in attendance only for an institutionally scheduled break. However, a scheduled break may occur during a LOA. A LOA must meet certain conditions to be counted as a temporary interruption in a student?s education instead of being counted as a withdrawal requiring an institution to perform a refund calculation. If an institution elects to offer LOAs, it must have a written Leave of Absence Policy that complies with this NACCAS Leave of Absence Policy and Checklist. Additionally, approval of a student?s LOA must be in accordance with the institution?s Leave of Absence Policy. A LOA may only be granted if there is a reasonable expectation that the student will return from the LOA. This checklist has been prepared as a guide to assist schools in interpreting the requirements of this Policy and to serve as a guide in preparing a Leave of Absence Policy. It is not necessary for the various elements to be stated in any special phraseology or listed in any particular sequence, as long as the overall policy conveys the required elements in a way that can be easily understood.",
#     "If an institution chooses to offer Leaves of Absence (LOAs), its Leave of Absence Policy must meet specific requirements and be submitted to the Commission along with a completed checklist each time the policy is provided, including as a required exhibit in the Institutional Self-Study (ISS). The policy must be clearly written and titled as a Leave of Absence Policy. It must state the acceptable reasons for granting a LOA and require students to follow institutional procedures when requesting one. The policy must require that students submit LOA requests in advance unless unforeseen circumstances prevent it, and such requests must be in writing, include the student’s reason and signature. If the LOA request is submitted after the LOA begins due to unforeseen events, the institution must document the reason, obtain the request later, and use the first day of the student’s absence as the start date. It must also state that students will not incur additional charges due to a LOA and that LOAs may not exceed a combined total of 180 days within a 12-month period. Furthermore, a student on an approved LOA is not considered withdrawn, so no refund calculation is required at that time. The policy must specify that the student’s contract period will be extended by the length of the LOA, and such changes must be confirmed either by initialing the updated enrollment agreement or signing an addendum. If a student takes an unapproved LOA or fails to return after an approved LOA ends, they are considered withdrawn. For refund calculations, if the institution takes attendance, the last date of attendance is used as the withdrawal date; if not, the withdrawal date is the day the LOA began. Additionally, the revised contract end date due to a LOA must not exceed a 15-day limit.",
#     "A student who is beyond the age of compulsory education, lacks a high school diploma or its equivalent, and has the ability to benefit from the education or training offered at an institution.",
#     "A school applying for NACCAS accreditation or in candidacy status cannot claim to be 'accredited by NACCAS' or imply accreditation in any way, as this would be misleading. However, if the school has been granted 'candidate status,' it may use the phrase 'candidate for accreditation' in its advertising. Schools that have never been accredited, have voluntarily relinquished accreditation, or have had accreditation withdrawn by NACCAS cannot advertise as accredited by NACCAS.",
#     "Yes, the use of 'Global Academy' on exterior signage and 'GACM' in social media advertising is permissible under the NACCAS policy, provided certain conditions are met. The policy allows the use of a shortened version of the school name (e.g., 'Global Academy' instead of 'Global Academy of Cosmetology and Massage') in instances where the school is clearly identifiable as the same institution. Similarly, abbreviations like 'GACM' are allowed in advertising, as the policy permits replacing words with numerical abbreviations or symbols (e.g., ampersands, Roman numerals) in promotional materials. However, the school must have listed any alternate names in its accreditation application, and the approved school name must be used on the institution’s homepage, though it is not required in the Social Media URL.",
#     "The school may advertise the 'Advanced Esthetics' pilot program, but it must adhere to the following requirements per the NACCAS policy: The school can advertise a maximum of one pilot program or course per year that does not yet have NACCAS approval to determine market interest. All advertising for the pilot program must clearly indicate that it is not yet accredited by NACCAS. This ensures transparency and prevents misleading prospective students about the program’s accreditation status.",
#     "No, a school named 'Elite Beauty Institute, LLC' cannot use 'LLC' in its advertising materials. The NACCAS policy prohibits the use of words, phrases, or abbreviations designating a corporate entity, such as 'Limited Liability Company' or 'LLC,' in the school’s name for advertising purposes. The school must advertise as 'Elite Beauty Institute' to comply with the policy.",
#     "To comply with NACCAS advertising standards, the school must: Ensure the claim ('90% of our graduates are employed within six months of graduation') is supported by current data sufficient to prove its truthfulness. Maintain the supporting data for a minimum of three years. Make the supporting data available for review by the Commission and the general public. Ensure the claim is accurate and not misleading, deceptive, fraudulent, or false, as required for all advertising directed at prospective students. Failure to meet these requirements would violate the policy’s standards for quantitative claims in advertising.",
#     "Yes, the transcript showing completion of a two-year associate’s degree program satisfies the educational requirements for admission, as the NACCAS policy recognizes proof of attainment of an associate’s degree or higher (via a college transcript showing college completion or degree) as an equivalent to a high school diploma. The school must maintain a copy of the college transcript in the student’s file to document this qualification.",
#     "The homeschooled student must provide the secondary school completion credential issued by the state to be eligible for enrollment, as the policy requires this credential if available in the state where the student was homeschooled. Additionally, the school must have a policy that explicitly states it accepts homeschooled students, and the student’s secondary school education must have been in a homeschool that state law treats as a home or private school.",
#     "No, a student who is still enrolled in high school cannot enroll in an associate’s degree program without a high school diploma. The NACCAS policy requires that for students enrolling in a program leading to an associate’s degree in lieu of completing high school, the student must no longer be enrolled in high school, must provide a high school transcript indicating they excelled in high school, and must satisfy the school’s written policy for admitting such students prior to the first day of class.",
#     "For ability-to-benefit (ATB) students, the school must maintain: Documentation of the results of each student’s test, verifying a passing score. Information on the third-party test administrator, including their name, address, and any identifier assigned by the test publisher or state. Alternatively, the policy allows ATB students to demonstrate their ability to benefit by satisfactorily completing 6 credit hours or 225 clock hours after enrollment, instead of taking a test prior to enrollment.",
#     "The school must ensure the student meets the admission requirements set out in the training agreement and any applicable state licensing or certification regulations. The student is not considered an enrollee of the NACCAS-accredited institution and is not counted in the NACCAS Annual Report. The school is not required to have a separate contract with the student but must maintain a copy of the training agreement along with a list of students enrolled through it. The agreement must specify the school’s obligations, such as reporting attendance and grades",
#     "The school must retain the student’s ATB-related records until at least 2029, as the policy requires records to be kept for a minimum of six years following the student’s completion of the program (2023 + 6 = 2029). The required records include documentation of the student’s satisfactory completion of 225 clock hours, counseling records, and records pertaining to the student’s enrollment.",
#     "No, this does not comply with the NACCAS Ability-to-Benefit Policy. For a 500-hour program, an ATB student must complete a nationally recognized, standardized, or industry-developed test prior to admission to demonstrate their ability to benefit, as the program is less than 600 hours and the post-enrollment option (6 credit hours or 225 clock hours) is not applicable. Admitting the student without meeting either requirement violates the policy.",
#     "No, this does not comply with the NACCAS Enrollment Agreement Requirements policy. The policy prohibits collecting any payments from an applicant, other than a non-refundable application fee not exceeding $100, before entering into an enrollment agreement. The $200 registration fee exceeds the allowed application fee and was collected prematurely, violating the policy.",
#     "A copy of the NACCAS Enrollment Agreement Checklist must accompany the enrollment agreement submitted to the Commission. The checklist serves as a guide to ensure the agreement contains all required elements per NACCAS standards and assists schools in interpreting accreditation standards when preparing contracts.",
#     "This does not comply with the NACCAS Policy on Occupational Associate Degree Programs for three reasons: While letters of recommendation from a former employer may justify an exception to the associate degree requirement, the policy requires that such documentation (e.g., letters) be available for review. Failing to retain the letters violates this requirement. The syllabus must include the date it was last reviewed as part of the minimum requirements. Omitting this date violates the syllabus requirements. The externship agreement must include evaluation criteria, along with specific learning objectives and course requirements. Lacking evaluation criteria violates the externship guidelines.",
#     "The minimum requirements for a course syllabus include: Title and course description. Course number. Course prerequisites and/or requisites. Instructional contact hours/credits. Learning objectives. Instructional materials and references. Topical outline of the course. Instructional methods. Out-of-class learning activities and assignments. Assessment criteria. Method of evaluating students. The date the syllabus was last reviewed.",
#     "To calculate the semester credit hours: Lecture: 300 clock hours ÷ 15 clock hours per semester credit hour = 20 semester credit hours. Lab: 300 clock hours ÷ 30 clock hours per semester credit hour = 10 semester credit hours. Clinical: 300 clock hours ÷ 45 clock hours per semester credit hour = 6.67 semester credit hours (rounded to 7, as partial credits are typically rounded up or per institutional policy). Total: 20 + 10 + 7 = 37 semester credit hours.",
#     "The disaster recovery plan must include: Financial Information: A written financial plan projecting the revenues, expenditures, and cash flow of the school at its location, including all startup costs (e.g., building, equipment, staffing) and projected enrollments and clinic revenues. Enrollment Information: Enrollment projections, including: Enrollment prior to the disaster. Returning students after the disaster. Projected enrollment at the current location",
#     "To comply with the NACCAS Policy on Disasters, the institution must: Notify NACCAS immediately of the cessation of teaching for days not listed in the catalog due to the hurricane damage. If the institution is unable to resume full compliance at its approved location within 30 calendar days, it must submit a written plan and timeline within 30 calendar days, detailing how it plans to resume operations. The notification must be sent to Darin M. Wallace, Esq., Executive Director 3015 Colvin Street, Alexandria, VA 22314 Phone: (703) 600-7600, Fax: (703) 379-2200 Email: dwallace@naccas.org",
#     "If the institution charges the student for extra instruction prior to the completion date on the enrollment agreement, it must secure an acknowledgment of credit to the student’s account for the payment. This ensures transparency and accountability for the charges applied before program completion",
#     "The institution can charge the student for the additional 30 hours of instruction because: The student has exhausted all allowed absences within the contract period. The enrollment agreement clearly states the amount charged per unit of instruction ($10 per clock hour). The institution must ensure: The tuition and fees information, including the $10 per clock hour charge, was provided to the student upon enrollment. If the student terminates before completing the contract, all monies received for the extra instruction (30 hours × $10 = $300) are refunded. If the institution charges the fee prior to the completion date on the enrollment agreement, it secures an acknowledgment of credit to the student’s account.",
#     "According to the NACCAS Minimum Tuition Adjustment Schedule, a student who completes 10% of the program (60 hours of a 600-hour program) owes 40% of the total tuition to the school. Any monies due to the student must be refunded within 45 calendar days of the determination of the official or unofficial withdrawal.",
#     "In the absence of state-mandated content, the Electrology program curriculum must include: Sciences: Infection control Electricity Anatomy and physiology Disease/Disorders (Hair, skin) Electrolysis: Use of Electrical Currents Modalities: Thermolysis, Galvanic, Blend Career and employment information: Professional ethics Communication skills Communication methods Income reporting Licensing or certification requirements State laws and regulations Business basics Record keeping The institution must also develop course outlines and use lesson plans that correlate to these components.",
#     "For a Hairdressing-only program in a state with no mandated curriculum content, the institution can exclude the following Cosmetology curriculum components: Principles and techniques for the skin (Skin care treatments, Makeup, Hair removal, Contraindications). Principles and techniques for the nails (Manicure, Pedicure, Artificial nails). The institution must still include: Sciences: Infection Control Chemistry Electricity Anatomy and physiology Structure/Disease/Disorders (Hair, Skin, Nails) Principles and techniques of Hair: Hair styling Hair shaping Hair coloring Chemical texture services Scalp and hair treatments Shampooing Career and employment information: Professional ethics Communication skills Compensation methods Income reporting Licensing or certification requirements State laws and regulations Business basics Record keeping",
#     "In the absence of state-mandated content, a Cosmetology program must include the following curriculum components: Sciences: Infection Control Chemistry Electricity Anatomy and physiology Structure/Disease/Disorders (Hair, Skin, Nails) Principles and techniques of Hair: Hair styling Hair shaping Hair coloring Chemical texture services Scalp and hair treatments Shampooing Principles and techniques for the skin (not required for Hairdressing-only programs): Skin care treatments Makeup Hair removal Contraindications Principles and techniques for the nails (not required for Hairdressing-only programs): Manicure Pedicure Artificial nails Career and employment information: Professional ethics Communication skills Compensation methods Income reporting Licensing or certification requirements State laws and regulations Business basics Record keeping",
#     "The institution must ensure that its distance education policy validates substantive and regular interaction as follows: Substantive Interaction: Engage students in teaching, learning, and assessment, including at least two of the following: Providing direct instruction. Assessing or providing feedback on student’s distance education coursework. Providing information or responding to questions about coursework content. Facilitating a group discussion regarding coursework content. Regular Interaction: Provide opportunities for substantive interactions with students on a scheduled basis. Monitor students’ academic engagement and ensure the instructor is responsible for substantive interaction.",
#     "To comply with the NACCAS Externship Requirements Policy: The institution must select the student based on written criteria and ensure the student meets these criteria. The student must have taken and passed a comprehensive written and practical examination establishing their qualification to participate in the externship course.",
#     "This does not fully comply with the NACCAS Internal Grievance Procedure Policy for two reasons: The policy requires students to be informed of the grievance policy at the beginning of the course or program. Failing to communicate the policy to the student at the program’s start violates this requirement. While the policy requires complaint forms to be made available to students, providing them only upon request may not meet the standard of being readily accessible, depending on how easily students can obtain them. To address the situation, the institution should: Immediately inform the student of the grievance policy and provide clear instructions on the steps to file a formal grievance, including access to the complaint form. Ensure the complaint form is provided promptly to the student. Revise its practices to ensure all future students are informed of the grievance policy at the beginning of their program and that complaint forms are readily available (e.g., through a student handbook, website, or physical copies in an accessible location). Retain records of the student’s complaint and its resolution for review by the NACCAS on-site visit team.",
#     "The institution must take the following steps: Notify the student that they are not meeting Satisfactory Academic Progress and that this impacts their eligibility for Title IV funds, as required by the policy. Place the student on SAP warning (if the institution uses this status) or proceed to probation if the student appeals. If the student appeals, evaluate the appeal based on the institution’s policy, which must include: How the student may re-establish eligibility for financial aid. Reasons for which a student may appeal, such as death of a relative, injury or illness of the student, or other allowable special circumstances. Documentation the student must submit explaining why they failed to make SAP and what has changed to allow achievement of SAP at the next evaluation. How the results of the appeal are documented in the student’s file. If the appeal is approved, place the student on probation if: The institution determines SAP standards can be met by the end of the subsequent evaluation period, or An academic plan is developed to ensure the student meets SAP requirements by a specific point within the maximum time frame. If the student does not prevail on appeal or fails to meet SAP during probation, they are no longer eligible for Title IV funds. The SAP policy must describe the appeal process, including the above elements, to ensure compliance.",
#     "The institution must take the following steps: Notify the student that they are not meeting Satisfactory Academic Progress, as required by the policy. Place the student on SAP warning (if the institution uses this status) or proceed to probation if the student appeals. If the student appeals, evaluate the appeal based on the institution’s policy, which must include: How the student may re-establish eligibility for financial aid (if applicable). Reasons for which a student may appeal, such as death of a relative, injury or illness of the student, or other allowable special circumstances. Documentation the student must submit explaining why they failed to make SAP and what has changed to allow achievement of SAP at the next evaluation. How the results of the appeal are documented in the student’s file. If the appeal is approved, place the student on probation if: The institution determines SAP standards can be met by the end of the subsequent evaluation period, or An academic plan is developed to ensure the student meets SAP requirements by a specific point within the maximum time frame. If the student does not prevail on appeal or fails to meet SAP during probation, they are no longer eligible for Title IV funds (if applicable). The SAP policy must describe the appeal process, including the above elements, to ensure compliance."
# ]

# # Print the number of QAs extracted
# print(f"Extracted {len(questions)} QAs.")

# # Generate, score, and save
# output_path = "/content/selfrag_qwen3_results.txt"
# with open(output_path, "w", encoding="utf-8") as f:
#     for i, (q, gt) in enumerate(zip(questions, ground_truths), 1):
#         try:
#             inputs = {"question": q}
#             start = time()

#             # Your streaming app call
#             for output in app.stream(inputs, {"recursion_limit": 20}):
#                 for _, value in output.items():
#                     pass

#             response = value["generation"]
#             end = time()

#             # Compute BERTScore
#             P, R, F1 = score([response], [gt], lang="en")
#             p, r, f1_score = P.item(), R.item(), F1.item()

#             # Write to file
#             f.write(f"Q{i}: {q}\nResponse: {response}\nGround Truth: {gt}\n")
#             f.write(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}\n")
#             f.write(f"Time: {end - start:.2f} sec\n{'-'*80}\n")

#             # Print to console
#             print(f"\nQ{i}: {q}")
#             print(f"Response: {response}")
#             print(f"Ground Truth: {gt}")
#             print(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}")
#             print(f"Time: {end - start:.2f} sec")
#             print("-" * 80)

#         except Exception as e:
#             f.write(f"Q{i}: {q}\n[Error during processing: {e}]\n{'-'*80}\n")
#             print(f"\nQ{i}: {q}\n[Error during processing: {e}]\n{'-'*80}")
#             continue

# # Download the result file
# files.download(output_path)