# -*- coding: utf-8 -*-
"""Self_RAG_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSCQ7XaIhf2nnzs2Gb4EkFNISXSu5Led
"""

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries
# %pip install langchain
# %pip install -qU langchain_community
# %pip install pypdf
!pip install faiss-cpu
# %pip install -U bitsandbytes
# %pip install -U transformers accelerate
!pip install -U langchain-huggingface
# === INSTALLS ===
!pip install -q langchain langchain-community pypdf transformers #accelerate
# %pip install -qU langchain-groq
# %pip install -qU langchain-groqpip install -U langchain-nomic langchain_community tiktoken langchainhub  langchain langgraph nomic[local]
from transformers import BitsAndBytesConfig
!pip install -U --quiet langgraph langchain-text-splitters
!pip install ragas
#!pip install git+https://github.com/explodinggradients/ragas.git
!pip install sacrebleu

# Import required modules from LangChain and other libraries
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA
from langchain_groq import ChatGroq
from langchain.prompts import PromptTemplate
from google import genai
from google.genai import types
from typing import List
from langchain.embeddings.base import Embeddings
from langchain.docstore.document import Document
from langchain_text_splitters import MarkdownHeaderTextSplitter
from typing import List
import os
import getpass

# Import the PyPDF loader from langchain_community
from langchain_community.document_loaders import PyPDFDirectoryLoader
# Define a function to load all PDF documents from a directory
def load_documents(data_path):
    return PyPDFDirectoryLoader(data_path).load()

# Define the path to the directory containing the PDF files and loading the PDF documents
pdfs_path="/content/drive/MyDrive/Deep_Dataset"
pdfs=load_documents(pdfs_path)

# Loading a pre-trained sentence embedding model from HuggingFace
embedding_model = HuggingFaceEmbeddings(
    model_name="Alibaba-NLP/gte-Qwen2-1.5B-instruct",
    model_kwargs={"trust_remote_code": True},
    encode_kwargs={"normalize_embeddings": True}
)

from langchain.vectorstores import FAISS

# Safely load your trusted FAISS index from local/Drive
vectordb = FAISS.load_local("/content/drive/MyDrive/QwenEmbeddings", embeddings=embedding_model,allow_dangerous_deserialization=True)
# Here deserialization means to convert a stored object (e.g in pickle format) to python code, which can be dangerous if file is from untrusted source

#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

if "GROQ_API_KEY" not in os.environ:
     os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

# === USE GROQ'S LLAMA3 ===
from langgraph.graph import MessagesState
from langchain.chat_models import init_chat_model

# changed according to langraph
model = init_chat_model("groq:meta-llama/llama-4-maverick-17b-128e-instruct", temperature=0.5, max_tokens=512, timeout=None)
# Initializing retriever
retriever=vectordb.as_retriever()

# Creating grader for doc retriever
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.pydantic_v1 import BaseModel, Field

# define a data class
class GradeDocuments(BaseModel):
    binary_score: str = Field(
        description="Documents are relevant to the question, 'yes' or 'no'"
    )

llm=model
# LLM with function call
structured_llm_grader = llm.with_structured_output(GradeDocuments)

system = """You are a grader assessing relevance of a retrieved document to a user question. \n
    Here is the retrieved document: \n\n {document} \n\n
    Here is the user question: {question} \n
    If the document contains keyword(s) or semantic meaning related to the user question, grade it as relevant. \n
    Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."""


# Prompt for the grader
# system = """You are a grader assessing relevance of a retrieved document to a user question. \n
#     If the document contains keyword(s) or semantic meaning related to the question, grade it as relevant. \n
#     Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."""

grade_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "Retrieved document: \n\n {document} \n\n User question: {question}"),
    ]
)

retrieval_grader = grade_prompt | structured_llm_grader


# testing grader
question = "what is employment assistance"
docs = retriever.invoke(question)
print(retrieval_grader.invoke({"question": question, "document": docs}))

# Generate Answer
from langchain import hub
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts import ChatPromptTemplate

# template = """"
# You are a helpful assistant that answers questions based on the following context
# Context: {context}
# Question: {question}
# Answer:

# """

template = (
    "You are an assistant for question-answering tasks regarding NACCAS policies. "
    "Use the following pieces of retrieved context to answer the question. "
    "If you don't know the answer, just say that you don't know. "
    "Use 25 sentences maximum and keep the answer concise.\n"
    "Question: {question} \n"
    "Context: {context}"
)

prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


rag_chain = prompt | llm | StrOutputParser()


# response
generation = rag_chain.invoke({"context": docs, "question": question})
generation

# create grader for hallucination
# define a data class
class GradeHallucinations(BaseModel):
    """Binary score for hallucination present in generation answer."""

    binary_score: str = Field(
        description="Answer is grounded in the facts, 'yes' or 'no'"
    )


# LLM with function call
structured_llm_grader = llm.with_structured_output(GradeHallucinations)

# prompt for the grader
system = """You are a grader assessing whether an LLM generation is grounded in / supported by a set of retrieved facts. \n
     Give a binary score 'yes' or 'no'. 'Yes' means that the answer is grounded in / supported by the set of facts."""
hallucination_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "Set of facts: \n\n {documents} \n\n LLM generation: {generation}"),
    ]
)

hallucination_grader = hallucination_prompt | structured_llm_grader
hallucination_grader.invoke({"documents": docs, "generation": generation})

# create grader for answer
# define a data class
class GradeAnswer(BaseModel):
    """Binary score to assess answer addresses question."""

    binary_score: str = Field(
        description="Answer addresses the question, 'yes' or 'no'"
    )

structured_llm_grader = llm.with_structured_output(GradeAnswer)

# prompt for the grader
system = """You are a grader assessing whether an answer addresses / resolves a question \n
     Give a binary score 'yes' or 'no'. Yes' means that the answer resolves the question."""
answer_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "User question: \n\n {question} \n\n LLM generation: {generation}"),
    ]
)

answer_grader = answer_prompt | structured_llm_grader
answer_grader.invoke({"question": question, "generation": generation})

### Question Re-writer

# Prompt
re_write_prompt = PromptTemplate(
    template="""You are a question re-writer that converts an input question to a better version that is optimized \n
     for vectorstore retrieval. Look at the initial and formulate an improved question. \n
     Here is the initial question: \n\n {question}. Improved question with no preamble: \n """,
    input_variables=["generation", "question"],
)

question_rewriter = re_write_prompt | llm | StrOutputParser()
question_rewriter.invoke({"question": question})

# define a data class for state
from typing import List
from typing_extensions import TypedDict

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: question
        generation: LLM generation
        documents: list of documents
    """

    question: str
    generation: str
    documents: List[str]


# # define graph steps
# from langchain.schema import Document

# all nodes
def retrieve(state):
    """
    Retrieve documents

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, documents, that contains retrieved documents
    """
    print("---RETRIEVE---")
    question = state["question"]

    # Retrieval
    documents = retriever.get_relevant_documents(question)
    return {"documents": documents, "question": question}


def generate(state):
    """
    Generate answer

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, generation, that contains LLM generation
    """
    print("---GENERATE---")
    question = state["question"]
    documents = state["documents"]

    # RAG generation
    generation = rag_chain.invoke({"context": documents, "question": question})
    return {"documents": documents, "question": question, "generation": generation}


def grade_documents(state):

    print("---CHECK DOCUMENT RELEVANCE TO QUESTION---")
    question = state["question"]
    documents = state["documents"]

    # Score each doc
    filtered_docs = []
    for d in documents:
        score = retrieval_grader.invoke(
            {"question": question, "document": d.page_content}
        )
        grade = score.binary_score
        if grade == "yes":
            print("---GRADE: DOCUMENT RELEVANT---")
            filtered_docs.append(d)
        else:
            print("---GRADE: DOCUMENT NOT RELEVANT---")
            continue
    return {"documents": filtered_docs, "question": question}


def transform_query(state):
    """
    Transform the query to produce a better question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates question key with a re-phrased question
    """

    print("---TRANSFORM QUERY---")
    question = state["question"]
    documents = state["documents"]

    # Re-write question
    better_question = question_rewriter.invoke({"question": question})
    return {"documents": documents, "question": better_question}



# Edges
def decide_to_generate(state):
    """
    Determines whether to generate an answer, or re-generate a question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Binary decision for next node to call
    """
    print("---ASSESS GRADED DOCUMENTS---")
    state["question"]
    filtered_documents = state["documents"]

    if not filtered_documents:
        # All documents have been filtered check_relevance
        # We will regenerate a new query
        print(
            "---DECISION: ALL DOCUMENTS ARE NOT RELEVANT TO QUESTION, TRANSFORM QUERY---"
        )
        return "transform_query"
    else:
        # We have relevant documents, go generate answer
        print("---DECISION: GENERATE---")
        return "generate"


def grade_generation_v_documents_and_question(state):
    """
    Determines whether the generation is grounded in the document and answers the question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Decision for next node to call
    """
    print("---CHECK HALLUCINATIONS---")
    question = state["question"]
    documents = state["documents"]
    generation = state["generation"]

    score = hallucination_grader.invoke(
        {"documents": documents, "generation": generation}
    )
    grade = score.binary_score

    # Check hallucination
    if grade == "yes":
        print("---DECISION: GENERATION IS GROUNDED IN DOCUMENTS---")
        # Check question-answering
        print("---GRADE GENERATION vs QUESTION---")
        score = answer_grader.invoke({"question": question, "generation": generation})
        grade = score.binary_score
        if grade == "yes":
            print("---DECISION: GENERATION ADDRESSES QUESTION---")
            return "useful"
        else:
            print("---DECISION: GENERATION DOES NOT ADDRESS QUESTION---")
            return "not useful"
    else:
        print("---DECISION: GENERATION IS NOT GROUNDED IN DOCUMENTS, RE-TRY---")
        return "not supported"

# Build graph
from langgraph.graph import END, StateGraph, START

workflow = StateGraph(GraphState)

# Define the nodes
workflow.add_node("retrieve", retrieve)
workflow.add_node("grade_documents", grade_documents)
workflow.add_node("generate", generate)
workflow.add_node("transform_query", transform_query)  # transform_query

# Build graph
workflow.add_edge(START, "retrieve")
workflow.add_edge("retrieve", "grade_documents")
workflow.add_conditional_edges(
    "grade_documents",
    decide_to_generate,
    {
        "transform_query": "transform_query",
        "generate": "generate",
    },
)

workflow.add_edge("transform_query", "retrieve")
workflow.add_conditional_edges(
    "generate",
    grade_generation_v_documents_and_question,
    {
        "not supported": "generate",
        "useful": END,
        "not useful": "transform_query",
    },
)

# Compile
app = workflow.compile()

# Final generation example  (relevant documents)
from pprint import pprint
import time
from pprint import pprint

# Start the timer
start_time = time.time()

inputs = {"question": "Can i make homeschooled students eligible for admision in my institute according to NACCAS?"}
for output in app.stream(inputs):
    for key, value in output.items():
        pprint(f"Node '{key}':")
    pprint("\n---\n")

# Final generation
pprint(value["generation"])

end_time = time.time()

# Print total execution time
print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")

# # Create a dataframe to store the question, context, and response
# inputs = {"question": "what is policy on training agreements?"}
# outputs = []


# for output in app.stream(inputs):
#     for key, value in output.items():
#         if key == "generate":  # Assuming 'generate' node produces the final output
#             question = value["question"]
#             documents = value["documents"]
#             generation = value["generation"]

#             # Combine document contents into a single string
#             context = "\n".join(doc.page_content for doc in documents)

#             # Append the result
#             outputs.append({
#                 "query": question,
#                 "context": context,
#                 "response": generation,
#             })

# import pandas as pd

# data = {
#     "question": ["What is the policy on training agreements?"],
#     "answer": [(
#         "When a NACCAS-accredited institution enters into a training agreement with a government agency, "
#         "school district, or other entity, it must meet the following conditions: "
#         "1) Maintain at least one student enrolled under its own enrollment agreement; "
#         "2) Students under training agreements are not counted as enrollees nor included in the NACCAS Annual Report; "
#         "3) A separate contract is not required for each student; "
#         "4) The institution must keep a copy of the training agreement with a list of students; "
#         "5) The agreement must specify the institution's obligations, such as attendance and grade reporting."
#     )],
#     "contexts": [[(
#         "If a NACCAS-accredited institution enters into a training agreement with a government agency, "
#         "school district, and/or other entity, it must ensure that the following conditions are met: "
#         "1. In order to comply with Section 1.2 of the NACCAS Rules of Practice and Procedure, accredited institutions must have at least one student who is contracted under its own enrollment agreement separate and apart from any training agreements; "
#         "2. Students attending under a training agreement are not considered enrollees of the NACCAS-accredited institution and are not counted in the NACCAS Annual Report; "
#         "3. The institution is not required to have a separate contract with each individual student enrolled under the training agreement; "
#         "4. The institution must maintain a copy of any training agreement with a list of students enrolled through the agreement; "
#         "5. The training agreement must specify what is expected of the NACCAS-accredited institution with regard to the contractual relationship (i.e. reporting of attendance and grades, etc.)."
#     )]],
#     "ground_truth": [(
#         "If a NACCAS-accredited institution enters into a training agreement with a government agency, "
#         "school district, and/or other entity, it must ensure that the following conditions are met: "
#         "1. At least one student must be enrolled under the institution’s own enrollment agreement; "
#         "2. Students under training agreements are not counted as enrollees nor in the NACCAS Annual Report; "
#         "3. No separate contract is required per student; "
#         "4. The institution must keep a copy of the training agreement with enrolled students; "
#         "5. The agreement must define the institution's responsibilities like attendance and grade reporting."
#     )]
# }

# from ragas import SingleTurnSample
# from ragas.metrics import BleuScore

# test_data = {
#     "user_input": "summarise given text\nThe company reported an 8% rise in Q3 2024, driven by strong performance in the Asian market. Sales in this region have significantly contributed to the overall growth. Analysts attribute this success to strategic marketing and product localization. The positive trend in the Asian market is expected to continue into the next quarter.",
#     "response": "The company experienced an 8% increase in Q3 2024, largely due to effective marketing strategies and product adaptation, with expectations of continued growth in the coming quarter.",
#     "reference": "The company reported an 8% growth in Q3 2024, primarily driven by strong sales in the Asian market, attributed to strategic marketing and localized products, with continued growth anticipated in the next quarter."
# }
# metric = BleuScore()
# test_data = SingleTurnSample(**test_data)
# metric.single_turn_score(test_data)

!pip install bert-score

from bert_score import score

response = ["According to NACCAS Policy IV.01, homeschooled students can be eligible for admission if they have evidence of completion of home schooling that state law treats as a home or private school, and if the state issues a credential for home schooling, the institution must maintain this credential."]
groundtruth = ["Yes, homeschooled students are eligible for admission into a NACCAS-accredited school if the school's policy allows it and their secondary education was in a homeschool treated as a home or private school by state law. The school must maintain evidence of completion or a state-issued credential if available."]

P, R, F1 = score(response, groundtruth, lang="en", verbose=True)
# print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")
print(f"BERTScore Precision: {P[0]:.4f}")
print(f"BERTScore Recall:    {R[0]:.4f}")
print(f"BERTScore F1:        {F1[0]:.4f}")