# -*- coding: utf-8 -*-
"""Self_RAG_v3(3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AObwoOgp01HrWZzdSRy8dYV_bLEjpaEZ
"""

# Commented out IPython magic to ensure Python compatibility.
# Install necessary libraries
# %pip install langchain
# %pip install -qU langchain_community
# %pip install pypdf
!pip install faiss-cpu
#%pip install -U bitsandbytes
# %pip install -U transformers accelerate
!pip install -U langchain-huggingface
# === INSTALLS ===
!pip install -q langchain langchain-community pypdf transformers #accelerate
# %pip install -qU langchain-groq
# %pip install -qU langchain-groqpip install -U langchain-nomic langchain_community tiktoken langchainhub  langchain langgraph nomic[local]
#from transformers import BitsAndBytesConfig
!pip install -U --quiet langgraph langchain-text-splitters
#!pip install ragas
#!pip install git+https://github.com/explodinggradients/ragas.git
!pip install sacrebleu
!pip install bert-score python-docx

# Import required modules from LangChain and other libraries
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA
from langchain_groq import ChatGroq
from langchain.prompts import PromptTemplate
from google import genai
from google.genai import types
from typing import List
from langchain.embeddings.base import Embeddings
from langchain.docstore.document import Document
from langchain_text_splitters import MarkdownHeaderTextSplitter
from typing import List
import os
import getpass

# Import the PyPDF loader from langchain_community
from langchain_community.document_loaders import PyPDFDirectoryLoader
# Define a function to load all PDF documents from a directory
def load_documents(data_path):
    return PyPDFDirectoryLoader(data_path).load()

# Define the path to the directory containing the PDF files and loading the PDF documents
pdfs_path="/content/drive/MyDrive/Deep_Dataset"
pdfs=load_documents(pdfs_path)

# from langchain.text_splitter import RecursiveCharacterTextSplitter
# Initialize=ing the text splitter to create overlapping chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
# # Splitting the loaded PDF documents into manageable text chunks
splits = text_splitter.split_documents(documents=pdfs)
# Loading a pre-trained sentence embedding model from HuggingFace
embedding_model = HuggingFaceEmbeddings(
    model_name="Qwen/Qwen3-Embedding-0.6B",
    model_kwargs={"trust_remote_code": True},
    encode_kwargs={"normalize_embeddings": True}
)
# Creating a FAISS based vector store from the text chunks using the embedding model
vectordb = FAISS.from_documents(splits, embedding_model) #Faiss is indexing the vectors created from wordembeddings, also note that embeddings are also created from splits in this step

# # Save the FAISS index to Google Drive (or any directory)
# vectordb.save_local("/content/drive/MyDrive/Qwen3Embeddings")

# from langchain.vectorstores import FAISS

# # Safely load your trusted FAISS index from local/Drive
# vectordb = FAISS.load_local("/content/drive/MyDrive/Qwen3Embeddings", embeddings=embedding_model,allow_dangerous_deserialization=True)
# # Here deserialization means to convert a stored object (e.g in pickle format) to python code, which can be dangerous if file is from untrusted source

#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

if "GROQ_API_KEY" not in os.environ:
     os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

# === USE GROQ'S LLAMA3 ===
from langgraph.graph import MessagesState
from langchain.chat_models import init_chat_model

# changed according to langraph
model = init_chat_model("groq:meta-llama/llama-4-maverick-17b-128e-instruct", temperature=0.5, max_tokens=512, timeout=None)
# Initializing retriever
retriever=vectordb.as_retriever()

# Creating grader for doc retriever
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.pydantic_v1 import BaseModel, Field

# define a data class
class GradeDocuments(BaseModel):
    binary_score: str = Field(
        description="Documents are relevant to the question, 'yes' or 'no'"
    )

llm=model
# LLM with function call
structured_llm_grader = llm.with_structured_output(GradeDocuments)

system = """You are a grader assessing relevance of a retrieved document to a user question. \n
    Here is the retrieved document: \n\n {document} \n\n
    Here is the user question: {question} \n
    If the document contains keyword(s) or semantic meaning related to the user question, grade it as relevant. \n
    Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."""


# Prompt for the grader
# system = """You are a grader assessing relevance of a retrieved document to a user question. \n
#     If the document contains keyword(s) or semantic meaning related to the question, grade it as relevant. \n
#     Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."""

grade_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "Retrieved document: \n\n {document} \n\n User question: {question}"),
    ]
)

retrieval_grader = grade_prompt | structured_llm_grader


# testing grader
question = "what is employment assistance"
docs = retriever.invoke(question)
print(retrieval_grader.invoke({"question": question, "document": docs}))

# Generate Answer
from langchain import hub
from langchain_core.output_parsers import StrOutputParser
from langchain.prompts import ChatPromptTemplate

# template = """"
# You are a helpful assistant that answers questions based on the following context
# Context: {context}
# Question: {question}
# Answer:

# """

template = (
    "You are an assistant for question-answering tasks regarding NACCAS policies. "
    "Use the following pieces of retrieved context to answer the question. "
    "If you don't know the answer, just say that you don't know. "
    "Use 25 sentences maximum and keep the answer concise.\n"
    "Question: {question} \n"
    "Context: {context}"
)

prompt = ChatPromptTemplate.from_template(template)

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


rag_chain = prompt | llm | StrOutputParser()


# response
generation = rag_chain.invoke({"context": docs, "question": question})
generation

# create grader for hallucination
# define a data class
class GradeHallucinations(BaseModel):
    """Binary score for hallucination present in generation answer."""

    binary_score: str = Field(
        description="Answer is grounded in the facts, 'yes' or 'no'"
    )


# LLM with function call
structured_llm_grader = llm.with_structured_output(GradeHallucinations)

# prompt for the grader
system = """You are a grader assessing whether an LLM generation is grounded in / supported by a set of retrieved facts. \n
     Give a binary score 'yes' or 'no'. 'Yes' means that the answer is grounded in / supported by the set of facts."""
hallucination_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "Set of facts: \n\n {documents} \n\n LLM generation: {generation}"),
    ]
)

hallucination_grader = hallucination_prompt | structured_llm_grader
hallucination_grader.invoke({"documents": docs, "generation": generation})

# create grader for answer
# define a data class
class GradeAnswer(BaseModel):
    """Binary score to assess answer addresses question."""

    binary_score: str = Field(
        description="Answer addresses the question, 'yes' or 'no'"
    )

structured_llm_grader = llm.with_structured_output(GradeAnswer)

# prompt for the grader
system = """You are a grader assessing whether an answer addresses / resolves a question \n
     Give a binary score 'yes' or 'no'. Yes' means that the answer resolves the question."""
answer_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system),
        ("human", "User question: \n\n {question} \n\n LLM generation: {generation}"),
    ]
)

answer_grader = answer_prompt | structured_llm_grader
answer_grader.invoke({"question": question, "generation": generation})

### Question Re-writer

# Prompt
re_write_prompt = PromptTemplate(
    template="""You are a question re-writer that converts an input question to a better version that is optimized \n
     for vectorstore retrieval. Look at the initial and formulate an improved question. \n
     Here is the initial question: \n\n {question}. Improved question with no preamble: \n """,
    input_variables=["generation", "question"],
)

question_rewriter = re_write_prompt | llm | StrOutputParser()
question_rewriter.invoke({"question": question})

# define a data class for state
from typing import List
from typing_extensions import TypedDict

class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question: question
        generation: LLM generation
        documents: list of documents
    """

    question: str
    generation: str
    documents: List[str]


# # define graph steps
# from langchain.schema import Document

# all nodes
def retrieve(state):
    """
    Retrieve documents

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, documents, that contains retrieved documents
    """
    print("---RETRIEVE---")
    question = state["question"]

    # Retrieval
    documents = retriever.get_relevant_documents(question)
    return {"documents": documents, "question": question}


def generate(state):
    """
    Generate answer

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): New key added to state, generation, that contains LLM generation
    """
    print("---GENERATE---")
    question = state["question"]
    documents = state["documents"]

    # RAG generation
    generation = rag_chain.invoke({"context": documents, "question": question})
    return {"documents": documents, "question": question, "generation": generation}


def grade_documents(state):

    print("---CHECK DOCUMENT RELEVANCE TO QUESTION---")
    question = state["question"]
    documents = state["documents"]

    # Score each doc
    filtered_docs = []
    for d in documents:
        score = retrieval_grader.invoke(
            {"question": question, "document": d.page_content}
        )
        grade = score.binary_score
        if grade == "yes":
            print("---GRADE: DOCUMENT RELEVANT---")
            filtered_docs.append(d)
        else:
            print("---GRADE: DOCUMENT NOT RELEVANT---")
            continue
    return {"documents": filtered_docs, "question": question}


def transform_query(state):
    """
    Transform the query to produce a better question.

    Args:
        state (dict): The current graph state

    Returns:
        state (dict): Updates question key with a re-phrased question
    """

    print("---TRANSFORM QUERY---")
    question = state["question"]
    documents = state["documents"]

    # Re-write question
    better_question = question_rewriter.invoke({"question": question})
    return {"documents": documents, "question": better_question}



# Edges
def decide_to_generate(state):
    """
    Determines whether to generate an answer, or re-generate a question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Binary decision for next node to call
    """
    print("---ASSESS GRADED DOCUMENTS---")
    state["question"]
    filtered_documents = state["documents"]

    if not filtered_documents:
        # All documents have been filtered check_relevance
        # We will regenerate a new query
        print(
            "---DECISION: ALL DOCUMENTS ARE NOT RELEVANT TO QUESTION, TRANSFORM QUERY---"
        )
        return "transform_query"
    else:
        # We have relevant documents, go generate answer
        print("---DECISION: GENERATE---")
        return "generate"


def grade_generation_v_documents_and_question(state):
    """
    Determines whether the generation is grounded in the document and answers the question.

    Args:
        state (dict): The current graph state

    Returns:
        str: Decision for next node to call
    """
    print("---CHECK HALLUCINATIONS---")
    question = state["question"]
    documents = state["documents"]
    generation = state["generation"]

    score = hallucination_grader.invoke(
        {"documents": documents, "generation": generation}
    )
    grade = score.binary_score

    # Check hallucination
    if grade == "yes":
        print("---DECISION: GENERATION IS GROUNDED IN DOCUMENTS---")
        # Check question-answering
        print("---GRADE GENERATION vs QUESTION---")
        score = answer_grader.invoke({"question": question, "generation": generation})
        grade = score.binary_score
        if grade == "yes":
            print("---DECISION: GENERATION ADDRESSES QUESTION---")
            return "useful"
        else:
            print("---DECISION: GENERATION DOES NOT ADDRESS QUESTION---")
            return "not useful"
    else:
        print("---DECISION: GENERATION IS NOT GROUNDED IN DOCUMENTS, RE-TRY---")
        return "not supported"

# Build graph
from langgraph.graph import END, StateGraph, START

workflow = StateGraph(GraphState) # create an empty graph template with data format mentioned in GraphState (GrpahStateDefines what data is passed around.)

# Define the nodes
workflow.add_node("retrieve", retrieve)
workflow.add_node("grade_documents", grade_documents)
workflow.add_node("generate", generate)
workflow.add_node("transform_query", transform_query)  # transform_query

# Build graph
workflow.add_edge(START, "retrieve")
workflow.add_edge("retrieve", "grade_documents") # grade documents function node checks whether passages are relevant to question or not
workflow.add_conditional_edges(
    "grade_documents",
    decide_to_generate,
    {
        "transform_query": "transform_query",
        "generate": "generate",
    },
)

workflow.add_edge("transform_query", "retrieve")
workflow.add_conditional_edges(
    "generate",
    grade_generation_v_documents_and_question,
    {
        "not supported": "generate",
        "useful": END,
        "not useful": "transform_query",
    },
)

# Compile
app = workflow.compile()

# Final generation example  (relevant documents)
from pprint import pprint
import time
from pprint import pprint

# Start the timer
start_time = time.time()

inputs = {"question": "What is refund policy?"}
for output in app.stream(inputs,{"recursion_limit": 5}):
    for key, value in output.items():
        pprint(f"Node '{key}':")
    pprint("\n---\n")

# Final generation
pprint(value["generation"])

end_time = time.time()

# Print total execution time
print(f"\nTotal Execution Time: {end_time - start_time:.2f} seconds")

# output_file = "qa_results.txt"

# with open(output_file, "w", encoding="utf-8") as f:
#     for i, question in enumerate(questions, start=1):
#         f.write(f"Q{i}: {question}\n")
#         print(f"Q{i}: {question}")
#         try:
#             response = qa_chain(question)  # Your QA chain call
#             answer = response['result']
#         except Exception as e:
#             answer = f"[Error: {str(e)}]"

#         f.write(f"A{i}: {answer}\n")
#         f.write("-" * 80 + "\n")

#         print(f"A{i}: {answer}")
#         print("-" * 80)

# from bert_score import score

# response = ["""The NACCAS Refund Policy requires that:
# 1. The policy is stated in clear language.
# 2. Applies to all terminations for any reason.
# 3. Complies with the mandated policy.
# 4. Refund calculations are performed and refunds are made timely.
# 5. Refunds are made within 45 calendar days of official cancellation or withdrawal.
# 6. A full refund is given if an applicant is not accepted by the school.
# Additionally, the policy may provide a pro rata refund for students transferring to another school or participating in a Teach-Out Agreement."""]

# groundtruth = ["Refund policy must comply with the NACCAS Withdrawal and Settlement Policy and Checklist and Minimum Tuition Adjustment Schedule and state or federal mandated policies."]

# P, R, F1 = score(response, groundtruth, lang="en", verbose=True)
# # print(f"Precision: {P.mean():.4f}, Recall: {R.mean():.4f}, F1: {F1.mean():.4f}")
# print(f"BERTScore Precision: {P[0]:.4f}")
# print(f"BERTScore Recall:    {R[0]:.4f}")
# print(f"BERTScore F1:        {F1[0]:.4f}")

!pip install bert-score python-docx

# from docx import Document
# from bert_score import score
# from time import time
# from google.colab import files

# # Load questions and ground truths from .docx
# def extract_qas(path):
#     doc = Document(path)
#     questions, truths = [], []
#     q, t, mode = "", "", None

#     for para in doc.paragraphs:
#         text = para.text.strip()
#         if not text: continue
#         if text[0].isdigit() and " " in text:
#             if q and t:
#                 questions.append(q.strip())
#                 truths.append(t.strip())
#             q, t, mode = text[text.find(" ")+1:], "", None
#         elif text.startswith("Ground Truth:"):
#             mode = "truth"
#         elif mode == "truth":
#             t += " " + text
#     if q and t:
#         questions.append(q.strip())
#         truths.append(t.strip())
#     return questions, truths

# # Load file
# docx_path = "/content/drive/MyDrive/model Generated Response and Scores(1).docx"
# questions, ground_truths = extract_qas(docx_path)

# # Generate, score, and save
# output_path = "/content/selfrag_qwen3_results.txt"
# with open(output_path, "w", encoding="utf-8") as f:
#     for i, (q, gt) in enumerate(zip(questions, ground_truths), 1):
#         try:
#             inputs = {"question": q}
#             start = time()

#             for output in app.stream(inputs, {"recursion_limit": 20}):
#                 for _, value in output.items(): pass

#             response = value["generation"]
#             end = time()

#             # Compute BERTScore
#             P, R, F1 = score([response], [gt], lang="en")
#             p, r, f1_score = P.item(), R.item(), F1.item()

#             # Write to file
#             f.write(f"Q{i}: {q}\nResponse: {response}\nGround Truth: {gt}\n")
#             f.write(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}\n")
#             f.write(f"Time: {end - start:.2f} sec\n{'-'*80}\n")

#             # Print to console
#             print(f"\nQ{i}: {q}")
#             print(f"Response: {response}")
#             print(f"Ground Truth: {gt}")
#             print(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}")
#             print(f"Time: {end - start:.2f} sec")
#             print("-" * 80)

#         except Exception as e:
#             f.write(f"Q{i}: {q}\n[Error during processing: {e}]\n{'-'*80}\n")
#             print(f"\nQ{i}: {q}\n[Error during processing: {e}]\n{'-'*80}")
#             continue

# # Download the result file
# files.download(output_path)

from docx import Document
from bert_score import score
from time import time
from google.colab import files
import re

# Improved QA extraction from .docx
def extract_qas(path):
    doc = Document(path)
    questions, truths = [], []
    q, t, mode = "", "", None

    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            continue

        # Match lines like: 1 What is...? or 2)What...? or 3. What...?
        match = re.match(r'^(\d+)[\.\)]?\s*(.+)', text)
        if match:
            if q and t:
                questions.append(q.strip())
                truths.append(t.strip())
            q = match.group(2).strip()
            t, mode = "", None
        elif text.lower().startswith("ground truth"):
            mode = "truth"
        elif mode == "truth":
            t += " " + text.strip()

    if q and t:
        questions.append(q.strip())
        truths.append(t.strip())

    return questions, truths

# Load file
docx_path = "/content/drive/MyDrive/model Generated Response and Scores(1).docx"
questions, ground_truths = extract_qas(docx_path)
print(f"Extracted {len(questions)} QAs.")

# Generate, score, and save
output_path = "/content/selfrag_qwen3_results.txt"
with open(output_path, "w", encoding="utf-8") as f:
    for i, (q, gt) in enumerate(zip(questions, ground_truths), 1):
        try:
            inputs = {"question": q}
            start = time()

            # Your streaming app call
            for output in app.stream(inputs, {"recursion_limit": 20}):
                for _, value in output.items():
                    pass

            response = value["generation"]
            end = time()

            # Compute BERTScore
            P, R, F1 = score([response], [gt], lang="en")
            p, r, f1_score = P.item(), R.item(), F1.item()

            # Write to file
            f.write(f"Q{i}: {q}\nResponse: {response}\nGround Truth: {gt}\n")
            f.write(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}\n")
            f.write(f"Time: {end - start:.2f} sec\n{'-'*80}\n")

            # Print to console
            print(f"\nQ{i}: {q}")
            print(f"Response: {response}")
            print(f"Ground Truth: {gt}")
            print(f"BERTScore -> P: {p:.4f}, R: {r:.4f}, F1: {f1_score:.4f}")
            print(f"Time: {end - start:.2f} sec")
            print("-" * 80)

        except Exception as e:
            f.write(f"Q{i}: {q}\n[Error during processing: {e}]\n{'-'*80}\n")
            print(f"\nQ{i}: {q}\n[Error during processing: {e}]\n{'-'*80}")
            continue

# Download the result file
files.download(output_path)

!apt-get install graphviz -y
!pip install graphviz

from graphviz import Source

dot = """
digraph LangGraphWorkflow {
    START -> retrieve;
    retrieve -> grade_documents;

    grade_documents -> transform_query [label="transform_query"];
    grade_documents -> generate [label="generate"];

    transform_query -> retrieve;

    generate -> END [label="useful"];
    generate -> generate [label="not supported"];
    generate -> transform_query [label="not useful"];
}
"""
Source(dot)